### ISSUE TITLE
ValueError: Cannot apply softmax to a tensor that is not 2D or 3D. Here, ndim=4

### ISSUE THREAD

**Issue by liuhuancom** [szad670401/HyperLPR#10]
跟着 [wiki](https://github.com/zeusees/HyperLPR/wiki/HyperLPR%E7%9A%84%E5%AE%89%E8%A3%85) 来，提示很多依赖没安装 安装完了在 jupyter notebook 中 `from hyperlpr import  pipline as  pp` 报错`ValueError: Cannot apply softmax to a tensor that is not 2D or 3D. Here, ndim=4`
不知道如何解决，请指教，先谢谢各位大神。

**Comment by cuicuizhang1989** [comment]
安装keras2.1不是2.0版本不对

**Comment by molyswu** [comment]
安装了keras2.1，重新编译:   ValueError: Cannot apply softmax to a tensor that is not 2D or 3D. Here, ndim=4
