### ISSUE TITLE
如果图片为行车记录仪记录下的视频的截图，会把图片中的时间也识别为车牌

### ISSUE THREAD

**Issue by BofengDuke** [szad670401/HyperLPR#101]

**Comment by BofengDuke** [comment]
添加说明： 这是在python3中，通过pip安装hyperlpr包时才有，如果使用hyperlprlite 是没有这个问题。

**Comment by panda-lab** [comment]
车牌检测的时候，有时候确实会遇到这个问题。我们考虑完善检测部分。

**Comment by axltfytx** [comment]
@lsy17096535这个是不是检测训练样本不够的问题？

**Comment by panda-lab** [comment]
@axltfytx 正样本要充分，负样本也要多样，才能降低错误识别。
