### ISSUE TITLE
8位绿色车牌无法识别

### ISSUE THREAD

**Issue by wannaRunaway** [szad670401/HyperLPR#107]
我将model和代码全部更新到了与linux同步最新，只能识别7位蓝色车牌，无法识别8位绿色车牌。

**Comment by panda-lab** [comment]
识别8位车牌，需要采用端到端模型，并修改输出字符长度。我们提供的模型可以识别。

**Comment by wannaRunaway** [comment]
**端到端模型不是linux中的，是总项目路径model吗？修改字符长度修改PlateSegmentation::templateMatchFinding这里吗：
  int cp_list[7];
        float loss_selected = -10;

        for(int start = 0 ; start < 20 ; start+=2)
            for(int  width = windowsWidth-5; width < windowsWidth+5 ; width++ ){
                for(int interval = windowsWidth/2; interval < windowsWidth; interval++)
                {
                    int cp1_ch  = start;
                    int cp2_p0 = cp1_ch+ width;
                    int cp3_p1 = cp2_p0+ width + interval;
                    int cp4_p2 = cp3_p1 + width;
                    int cp5_p3 = cp4_p2 + width+1;
                    int cp6_p4 = cp5_p3 + width+2;
                    int cp7_p5= cp6_p4+ width+2;

**Comment by wannaRunaway** [comment]
好的，感谢各位大佬，android 手机绿色新能源车牌可以识别了，使用端到端可以识别。

**Comment by kingslou** [comment]
> 识别8位车牌，需要采用端到端模型，并修改输出字符长度。我们提供的模型识别。

能在文档中说明一下吗 谢谢

**Comment by kingslou** [comment]
> 好的，感谢各位大佬，android 手机绿色新能源车牌可以识别了，使用端到端可以识别。

能把改动的地方 说明一下吗 谢谢
