### ISSUE TITLE
Opencv 版本问题

### ISSUE THREAD

**Issue by DanielXu123** [szad670401/HyperLPR#108]
您好.
我想请问一下再Linux Ubuntu系统下运行, OpenCV 能使用 Opencv-python吗?还是说一定要安装独立的3.3.0 版本的OpenCV?

在Linux中编译的过程中总是出现关于OpenCV库寻找不到的问题. 但是我安装了python 版本的opencv,所以已经可以成功import cv2. 是否可以在哪里修改调取OpenCV的路径,然后成功调用Python版本的OpenCV来成功编译呢?

**Comment by panda-lab** [comment]
最好自己编译3.3以上版本的opencv，并编译python接口。
ubuntu系统中，自己编译的python opencv应该在python目录下的 \Python27\Lib\site-packages 目录中。

**Comment by DanielXu123** [comment]
您好,谢谢您的回复

我能找到我自己系统里的python opencv的路径, which is under the path of Anaconda

就是我想问的是,执行编译 

cd Prj-Linux
mkdir build 
cd build
cmake ../
sudo make -j 

执行到 cmake ../ 这步骤时,我能不能指定让程序选择使用我自己指定路径下的OPENCV,应该如何指定?是修改bashrc 文件里添加OPENCV的路径,类似于这样吗?

export OPENCVPATH ="/home/DanielXu/miniconda2/envs/tensorflow/lib/python3.5/site-packages/opencv_python-3.4.3.18.dist-info:$OPENCVPATH"

**Comment by panda-lab** [comment]
OpenCV要指定你编译安装的位置，如果通过apt get安装，请查看默认目录。
