### ISSUE TITLE
how to train SegmenationFree-Inception.caffemodel?

### ISSUE THREAD

**Issue by axltfytx** [szad670401/HyperLPR#109]
HorizonalFinemapping.caffemodel
HorizonalFinemapping.prototxt
SegmenationFree-Inception.caffemodel
SegmenationFree-Inception.prototxt

**Comment by panda-lab** [comment]
HorizonalFinemapping.caffemodel is a basic regression network, you can reference mtcnn-onet structure.
SegmenationFree-Inception.caffemodel you can reference the training code provided by ReadMe.

**Comment by panda-lab** [comment]
HorizonalFinemapping.caffemodel is a basic regression network, you can reference mtcnn-onet structure.
SegmenationFree-Inception.caffemodel you can reference the training code provided by ReadMe.
