### ISSUE TITLE
精定位无法识别奥迪车牌？

### ISSUE THREAD

**Issue by axltfytx** [szad670401/HyperLPR#110]
![default](https://user-images.githubusercontent.com/43292251/47282405-a8d32c80-d611-11e8-9105-24a25d8ea54a.JPG)
类似奥迪这种车牌，粗定位没有，能截取到车牌，但是都无法识别，是竖格导致精定位失败？

**Comment by panda-lab** [comment]
这种识别应该是没有问题，你需要根据场景调整检测器的最小、最大尺寸。

**Comment by axltfytx** [comment]
@lsy17096535 我没说清楚，检测是没问题的，这是检测后截取的车牌，但是无法识别，你可以试试
