### ISSUE TITLE
号码中的L总是识别不出来

### ISSUE THREAD

**Issue by laorient** [szad670401/HyperLPR#111]
苏Lxxxxx中的L字总是识别不出来，比如苏L7006X变成苏7006X。

C++版RunPipelineAsImage
![7006x](https://user-images.githubusercontent.com/1508039/47338076-6c242700-d64b-11e8-85be-70097b090f6e.jpg)

**Comment by panda-lab** [comment]
测试c++版的端到端模型，或者直接用python版。

**Comment by laorient** [comment]
> 测试c++版的端到端模型，或者直接用python版。

你是说重新训练吗？Python版的效率很低，而且两个使用的是一个Model，应该不会有区别吧。

**Comment by laorient** [comment]
借用了prj-Linux里的Segmentation Free Mode的代码，结果好很多。
