### ISSUE TITLE
为什么我老是出现这个问题啊，该安装都安装了呀？

### ISSUE THREAD

**Issue by LamzZ2** [szad670401/HyperLPR#115]
![qq 20181107210522](https://user-images.githubusercontent.com/35766481/48133174-e8b43800-e2d0-11e8-9dbb-2fcb626beee2.png)

**Comment by axltfytx** [comment]
你的执行目录不对，直接到安装目录下执行脚本即可，你用的哪种安装方式？pip？

**Comment by LamzZ2** [comment]
> 你的执行目录不对，直接到安装目录下执行脚本即可，你用的哪种安装方式？pip？

对的 我是用pip安装的

**Comment by axltfytx** [comment]
如果是Anaconda3，请到此目录x:\Anaconda3\Lib\site-packages目录下进入hyperlpr目录执行，否则建议设置环境变量

**Comment by sesky4** [comment]
hyperlrp.HyperLPR_PlateRecogntion(img)

python不会？

**Comment by dajiangyou333** [comment]
兄弟，你是怎么解决的
