### ISSUE TITLE
android版本编译时C代码不能编译过去

### ISSUE THREAD

**Issue by beeagle2018** [szad670401/HyperLPR#123]
Build command failed.

Error while executing process E:\Android\android-sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HD:\beeagle\source\android\HyperLPR-master\Prj-Android\app\src\main\cpp -BD:\beeagle\source\android\HyperLPR-master\Prj-Android\app\.externalNativeBuild\cmake\release\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-23 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\beeagle\source\android\HyperLPR-master\Prj-Android\app\build\intermediates\cmake\release\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=E:\Android\android-sdk\ndk-bundle -DCMAKE_CXX_FLAGS=-std=c++11 -DCMAKE_TOOLCHAIN_FILE=E:\Android\android-sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=E:\Android\android-sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_STL=gnustl_static}

 (include)   CMakeLists.txt 
Open File

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage

CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage

-- Configuring incomplete, errors occurred!

Build command failed.

Error while executing process E:\Android\android-sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HD:\beeagle\source\android\HyperLPR-master\Prj-Android\app\src\main\cpp -BD:\beeagle\source\android\HyperLPR-master\Prj-Android\app\.externalNativeBuild\cmake\debug\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-23 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\beeagle\source\android\HyperLPR-master\Prj-Android\app\build\intermediates\cmake\debug\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=E:\Android\android-sdk\ndk-bundle -DCMAKE_CXX_FLAGS=-std=c++11 -DCMAKE_TOOLCHAIN_FILE=E:\Android\android-sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=E:\Android\android-sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_STL=gnustl_static}

 (include)   CMakeLists.txt 
Open File

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage

CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage

-- Configuring incomplete, errors occurred!

**Comment by LeonTsang** [comment]
下载稳定版的ndk

**Comment by elrondliu** [comment]
ndk用14b
