### ISSUE TITLE
倾斜的车牌识别不出来

### ISSUE THREAD

**Issue by zhangting1994** [szad670401/HyperLPR#124]
from hyperlpr import *
#导入OpenCV库
import cv2
#读入图片
image = cv2.imread("demo.jpg")
#识别结果
print(HyperLPR_PlateRecogntion(image))
用这个我发现倾斜的车牌识别不出来是怎么回事

**Comment by 2017TJM** [comment]
我也是觉得，应该是字符分割或者定位那块做的不够好

**Comment by panda-lab** [comment]
定位不是很厉害，大家可以自己训练分类器，优化一下。
