### ISSUE TITLE
SegmenationFree-Inception模型训练问题

### ISSUE THREAD

**Issue by shenjackson** [szad670401/HyperLPR#127]
请问端到端的SegmenationFree-Inception模型怎么训练呢

**Comment by panda-lab** [comment]
训练代码已经提供了

**Comment by shenjackson** [comment]
谢谢回复，是hyperlpr-train这个代码吗

**Comment by shenjackson** [comment]
我用hyperlpr-train_e2e这个代码训练自己数据不收敛
loss总是在96.5浮动，

**Comment by 0801130205** [comment]
请问SegmenationFree-Inception训练时进行数据准备过程中,label是什么样的?模型的输出的长度为20,而中文车牌长度为7或8,那么准备训练数据时label如何把长度为7或8的车牌号码编码到长度为20?

**Comment by soufianesabiri** [comment]
Can you provide code with GRU enabled?

**Comment by Rick51** [comment]
你好，我最近也在考虑finetune这个模型，想问下后来你有解决这个问题吗？方便的话可以加微信私聊么。感谢回复
