### ISSUE TITLE
Linux 版 CPU 占用 300% 以上

### ISSUE THREAD

**Issue by gmg137** [szad670401/HyperLPR#128]
如题，使用 linux 版车牌识别，CPU占用一直保持在 300% 以上，求教这个该怎么优化?

**Comment by gmg137** [comment]
补充，在使用视频流采集的时候会发生这种情况，视频调到3帧以下cpu占用降至100%左右，不然进程会直接被杀死。

**Comment by panda-lab** [comment]
你写一个线程调用识别的方法

**Comment by gmg137** [comment]
对cpp不是很了解，我是从其它语言调cpp接口用的，你可以直接从视频采集试试。

下面是linux下top的输出:
![2018-12-17 13-08-07](https://user-images.githubusercontent.com/6460323/50067744-5ff8b800-01fd-11e9-85e1-00f7c9ae22c5.png)

下面是: top -H -p
![2018-12-17 13-08-45](https://user-images.githubusercontent.com/6460323/50067749-7141c480-01fd-11e9-9e69-293d72cc9eba.png)

**Comment by gmg137** [comment]
问题已经解决！

**Comment by PHI6kai** [comment]
@gmg137 您好想问一下您是怎么解决的我也有类似的问题
