### ISSUE TITLE
ModuleNotFoundError: No module named 'hyperlpr'

### ISSUE THREAD

**Issue by shayxurui** [szad670401/HyperLPR#129]
你好，感谢分享代码。我已经通过pip install hyperlpr命令安装了，可是当import hyperlpr却报错？请问是什么原因？

**Comment by suyuvitamin** [comment]
是不是得要在安装目录下运行才行啊，C:\Users\Administrator\AppData\Local\Programs\Python\Python36\HyperLPR-master，这个路径

**Comment by mattzhang1984** [comment]
用python -m pip install hyperlpr
