### ISSUE TITLE
最新端到端的车牌检测

### ISSUE THREAD

**Issue by zhDai** [szad670401/HyperLPR#13]
你好，如果我想训练最新的端到端模型，训练数据标签怎么弄的？因为我我看到最后卷积层是len(e2e.chars)+1（84）个输出结果

**Comment by szad670401** [comment]
85=84个是单个label vector的长度+1个空白标签

**Comment by zhDai** [comment]
有训练的文件吗？不知可以参看下吗

**Comment by szad670401** [comment]
训练文件暂时还未整理，过段时间吧
