### ISSUE TITLE
运行安装目录的demo时出现了一个Invalid  syntax

### ISSUE THREAD

**Issue by suyuvitamin** [szad670401/HyperLPR#130]
总是提示print "Image size :" + str(grr.shape[1])+"x"+str(grr.shape[0]) +  " need " + str(round(t*1000,2))+"ms"这一句中的:（冒号）后面那个引号 :" 有错误，运行环境都安装了，Python版本是3.6

**Comment by kkxl490** [comment]
遇到了同样的问题，你解决了吗

**Comment by Aatroxs** [comment]
我也是

**Comment by xiaoyaomimi** [comment]
代码是python2的，print方法要改
