### ISSUE TITLE
loss函数 ocr_plate_all_gru.h5

### ISSUE THREAD

**Issue by 12281001** [szad670401/HyperLPR#131]
您好！

我最近在学习车牌识别，试用了ocr_plate_all_gru.h5来识别车牌，发现其预测出来的结果是1*18*84，我知道1表示图像个数batch， 84为84种分类，18我猜为18个字符，但觉得不对，我想问的问题是：
          1. 18表示含义是？
          2. ocr_plate_all_gru.h5这个模型在train中 loss是怎么算的？ 主要是18没有理解透，因为正常车牌没有18个字符，所以输出结果和车牌的实际车牌号之间loss是怎么算的。

非常感谢！

**Comment by GreenVegetables123** [comment]
同问，因为需要重新训练，还有一个问题是我看y_pred=y_pred[:,2:,:],不知道为什么要从２开始算起？

**Comment by huangyiping-ai** [comment]
@12281001，你好，ocr_plate_all_w_rnn_2.h5模型是用ctc loss作为损失函数的，18为18个时刻，是时间序列，ocr_plate_all_gru.h5在OCR模型上加入GRU单元，所以我猜测它的损失函数也是ctc loss

**Comment by huangyiping-ai** [comment]
@12281001，你好，ocr_plate_all_w_rnn_2.h5模型是用ctc loss作为损失函数的，18为18个时刻，是时间序列。ocr_plate_all_gru.h5在OCR模型上加入GRU单元，因为没看见训练代码，所以我猜测它的损失函数也是ctc loss，仅供参考哈！

**Comment by panda-lab** [comment]
@huangyiping-ai 感谢你的解答，是的，这个模型的训练就是采用ctc loss。
