### ISSUE TITLE
C++ 版代码检测栏杆成车牌

### ISSUE THREAD

**Issue by gmg137** [szad670401/HyperLPR#132]
![hhhhhw-1545793272](https://user-images.githubusercontent.com/6460323/50437412-9e405680-0924-11e9-960e-86413cb5d957.jpg)
![g0238m](https://user-images.githubusercontent.com/6460323/50437493-e495b580-0924-11e9-814e-6432f1c0f155.jpg)

如图，背景栏杆被识别成了 "甘HHHHHW" 或者 "川111111"

**Comment by panda-lab** [comment]
定位算法有待提高，我们会继续完善的。
