### ISSUE TITLE
FastDeskew.cpp 中的angle函数 atan2(x,y)应为atan2(y,x)

### ISSUE THREAD

**Issue by JempChou** [szad670401/HyperLPR#133]
在FastDeskew.cpp的    
int angle(float x,float y){
        return atan2(x,y)*180/3.1415;    
}里atan2函数是函数原型是atan2( y , x )，这里写的是 atan2(x,y)

**Comment by northeastsquare** [comment]
后面求了余角

**Comment by northeastsquare** [comment]
顺便问一句，correctPlateImage，函数看懂了吗？我没有看懂，谁看懂给讲讲，谢谢

**Comment by AlanNewImage** [comment]
correctPlateImage是为了把车牌转正，fastdeskew就是根据轮廓信息，计算车牌角度然后将车牌转正。
