### ISSUE TITLE
ValueError: You are trying to load a weight file containing 13 layers into a model with 11 layers.

### ISSUE THREAD

**Issue by ShaneYS** [szad670401/HyperLPR#134]
原始版本的hyperlpr使用的识别模型是ocr_plate_all_w_rnn_2.h5，可以正常使用。
我在hyperlpr_py3/e2e.py中把识别模型改为ocr_plate_all_gru.h5，然后再次运行的时候报错：
ValueError: You are trying to load a weight file containing 13 layers into a model with 11 layers.

请问这个是什么原因？
谢谢

详细错误：
Traceback (most recent call last):
  File "/home/ys/LPR/My_HyperLPR/HyperLPR/prac.py", line 2, in <module>
    from hyperlpr_py3 import pipline as pp
  File "/home/ys/LPR/My_HyperLPR/HyperLPR/hyperlpr_py3/pipline.py", line 24, in <module>
    from . import e2e
  File "/home/ys/LPR/My_HyperLPR/HyperLPR/hyperlpr_py3/e2e.py", line 17, in <module>
    pred_model = model.construct_model("./model/ocr_plate_all_gru.h5",)
  File "/home/ys/LPR/My_HyperLPR/HyperLPR/hyperlpr_py3/e2emodel.py", line 33, in construct_model
    base_model.load_weights(model_path)
  File "/home/ys/.local/lib/python3.5/site-packages/keras/engine/topology.py", line 2622, in load_weights
    load_weights_from_hdf5_group(f, self.layers)
  File "/home/ys/.local/lib/python3.5/site-packages/keras/engine/topology.py", line 3115, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 13 layers into a model with 11 layers.

**Comment by panda-lab** [comment]
两个模型的结构不一样，你可以采用loadmodel函数载入，别用loadweight

**Comment by Robbie-Xu** [comment]
> 两个模型的结构不一样，你可以采用loadmodel函数载入，别用loadweight

您好，可以请教一下具体的方法吗，将pred_model = model.construct_model("./model/ocr_plate_all_w_rnn_2.h5",)
改为pred_model = load_model("./model/ocr_plate_all_gru.h5",)后keras报错了
ValueError: Unknown loss function:<lambda>

查了一下需要指定loss函数，原本以为是e2emodel.py 中的ctc_lambda_func，但改为pred_model = load_model("./model/ocr_plate_all_gru.h5",custom_objects={'<lambda>':model.ctc_lambda_func})后，还是有问题，TypeError: ctc_lambda_func() takes 1 positional argument but 2 were given
请问正确的写法应该是怎么样的呢

**Comment by panda-lab** [comment]
@szad670401 帮忙看一下哈

**Comment by Robbie-Xu** [comment]
> @szad670401 帮忙看一下哈

谢谢关注，我上面的回复写法有些问题，为了方便大佬们查看错误，修正一下
一是ValueError完整是ValueError: Unknown loss function:<lambda>
二是pred_model = load_model("./model/ocr_plate_all_gru.h5",custom_objects={'':model.ctc_lambda_func})这句，括号里应为{'<lambda>':model.ctc_lambda_func}
以上是我运行时的写法，搬到回复时没有注意到写错了。

究极小白，照猫画虎改的，感谢大佬指出问题。
