### ISSUE TITLE
pip安装用示例代码直接使用，从项目里拿出来的图片能识别，我自己传的不能识别

### ISSUE THREAD

**Issue by huigangwang** [szad670401/HyperLPR#135]
这是项目里拿的图片和结果
![11](https://user-images.githubusercontent.com/43035907/50753193-f748ac80-128b-11e9-906d-55c636a8a532.jpg)
![xm](https://user-images.githubusercontent.com/43035907/50753219-0a5b7c80-128c-11e9-9655-008ab2d72e35.png)

这是网上找的图片和结果
![1](https://user-images.githubusercontent.com/43035907/50753243-1e06e300-128c-11e9-9543-9c7bca931e0a.jpg)
![zj](https://user-images.githubusercontent.com/43035907/50753249-252df100-128c-11e9-804d-fc9795772513.png)

问一下是哪里有问题吗？我想既然项目里的图片能识别出来，网上找的就没啥问题，为啥会是空的

**Comment by panda-lab** [comment]
查看一下是否检测到了车牌

**Comment by huigangwang** [comment]
> 查看一下是否检测到了车牌

我的图片没找到车牌，我把我图片里的车牌截图出来贴到项目里图片中的车牌位置，也一样找不到车牌

**Comment by szad670401** [comment]
把最后一个参数 charSelectionDeskew=True 设为False试试看。

**Comment by MrYZD** [comment]
我也遇到同样的问题，charSelectionDeskew=False 设置成这样也不行，detectPlateRough 方法返回空数组。

**Comment by huigangwang** [comment]
> 我也遇到同样的问题，charSelectionDeskew=False 设置成这样也不行，detectPlateRough 方法返回空数组。

应该是训练的模型场景不通用的问题，或者训练的模型只在训练数据上能够识别这样的

**Comment by monoloxo** [comment]
空数组应该是没检测到车牌吧，奇葩的是我有一张图片，明明只有一个车牌，却识别出两个。。。

**Comment by panda-lab** [comment]
@monoloxo 检测算法还不够好。
