### ISSUE TITLE
闽O的车牌识别成闽D或者闽新

### ISSUE THREAD

**Issue by Kimgtb** [szad670401/HyperLPR#138]
闽O的车牌识别成闽D或者闽新
![10](https://user-images.githubusercontent.com/8787046/51435150-9f5a6e80-1cab-11e9-9e21-365ef0eefdb9.jpg)

**Comment by rochesterlmg** [comment]
请问你用的是哪种训练集，是不是其中D的数据量不够啊？

**Comment by panda-lab** [comment]
是我们没有O的车牌数据集
