### ISSUE TITLE
请问HyperLPR能进行加速吗

### ISSUE THREAD

**Issue by liwfpgz** [szad670401/HyperLPR#139]
请问，HyperLPR的C++版本可以加速吗，比如用cuda。有人知道吗

**Comment by szad670401** [comment]
opencv 的dnn可以通过halide backend 调用cuda 或者 原生opencl 来加速

**Comment by liwfpgz** [comment]
我测试过了，大部分耗时是在车牌检测部分，字符识别部分耗时比较少，因此dnn加速也减少不了多少时间

**Comment by panda-lab** [comment]
@liwfpgz 检测部分确实需要进一步优化，我们也在想办法。

**Comment by lanybass** [comment]
c++，windows版，测试400*400左右的jpg图片，平均400ms
能把android版所谓的实时检测移过来？

**Comment by panda-lab** [comment]
Android速度快是因为图片分辨率低，检测方法是一样的。
