### ISSUE TITLE
如何使用安卓项目

### ISSUE THREAD

**Issue by Ten000hours** [szad670401/HyperLPR#14]
如何将安卓项目导入Android studio并使用

**Comment by szad670401** [comment]
正常导入 
接着添加opencv3.3 的包 即可

**Comment by Ten000hours** [comment]
不好意思 我不是很理解，我是直接用Android studio3.0.1中的git直接clone，之后无法生成gradle（版本为4.1），有什么解决办法吗

**Comment by szad670401** [comment]
工程的target sdk是7.0

**Comment by 603751448** [comment]
我也是直接用Android studio3.0.1，直接clone，但是导入项目中无法编译。
提示错误：Build command failed.一大段话，因为刚接触这类型项目，不太懂，希望大佬帮助一下

**Comment by DoneMr** [comment]
CMake有需要改动的地方，但是具体不知道怎么配置，先集成的openCV，再来集成大佬的代码，cmkae还是一堆错，求大佬指教

**Comment by hbzha** [comment]
想做车牌识别方面的，openCV的库太大了，5M左右，有什么办法可以减小？

**Comment by panda-lab** [comment]
@hbzha 把opencv dnn 模块单独编译
