### ISSUE TITLE
关于打包的一些问题

### ISSUE THREAD

**Issue by monoloxo** [szad670401/HyperLPR#140]
有人能够告诉我是怎么把深度模型打包到一起，可以让人用pip安装的吗？这部分用到什么知识？
还有为什么pip安装的方式不再对深度学习框架有需求就可以运行，例如我看到的是caffe的model，可我本机并没有装caffe，它是怎么能够调用模型并进行工作的呢？对这方面的知识很好奇，有人能指个方向吗？谢谢

**Comment by panda-lab** [comment]
opencv 3.3以上的版本dnn模块可以直接调用caffe model，打包没有固定的方式，可以按照自己的方式打包在一起。
