### ISSUE TITLE
端到端(CTC)训练出来的模型文件使用问题？

### ISSUE THREAD

**Issue by xiasys001** [szad670401/HyperLPR#141]
请问下端到端(CTC)训练出来的模型文件是替换model目录下char_judgement.h5吗？
我直接替换运行后报模型中的层不对应错：

ValueError: You are trying to load a weight file containing 11 layers into a model with 4 layers.

**Comment by panda-lab** [comment]
训练模型跟载入的模型不一致，你看下你的模型结构。

**Comment by xiasys001** [comment]
@lsy17096535   
model目录下的模型文件 跟 Prj-Linux/lpr/model的模型文件 有什么区别？
到端(CTC)训练出来的模型文件不能用到Prj-Linux/lpr/下的 吧?

**Comment by ShaneYS** [comment]
你好，请问你解决这个问题了吗

**Comment by little2Rabbit** [comment]
训练的和识别的模型层数网络数不一样，肯定不能识别啊，要自己改

**Comment by panda-lab** [comment]
@qq542288564  是的。
