### ISSUE TITLE
Android使用了端对端模型识别，但还是识别不了新能源车牌

### ISSUE THREAD

**Issue by AliceYangs** [szad670401/HyperLPR#142]
Android工程，我将模型都换为linux下面最新的模型，并改为端对端模型识别，但还是识别不了8位新能源车牌，只能识别普通7位蓝牌

**Comment by xiasys001** [comment]
端对端模型识别你改了什么地方？

**Comment by AliceYangs** [comment]
![image](https://user-images.githubusercontent.com/43170504/53070960-b0510680-351b-11e9-82a8-0d72c2ea46ee.png)

**Comment by chris1206** [comment]
我运行的apk demo就根本识别不了新能源车牌
