### ISSUE TITLE
MobileNet-300-0.25-ssd 在E5-2650服务器上cpu运行需要120毫秒

### ISSUE THREAD

**Issue by CLoudSnowMan** [szad670401/HyperLPR#143]
就用这个python脚本运行 依赖opencv dnn模块 cpu运行需要120毫秒 作者说7毫秒，请问差距这么大哇

**Comment by panda-lab** [comment]
看一下你的图片分辨率，另外，应该你的opencv 没有开启AVX 加速编译，不然不会这么慢。

**Comment by CLoudSnowMan** [comment]
cvNet.setInput(cv.dnn.blobFromImage(img, size=(300, 300), swapRB=True, crop=False))
将这个size改了之后，运行时间是6毫秒，
第一我是pip install opencv-python=4.0 安装的4.0，这里默认开启了AVX吗，
第二，img= cv.cvtColor(img,cv.COLOR_BGR2GRAY)
    img = cv.cvtColor(img,cv.COLOR_GRAY2RGB)，看起来网络支持输入为灰度图像啊

**Comment by panda-lab** [comment]
输入图像分辨率512*512以下能达到7ms
