### ISSUE TITLE
Android 使用Linux下面的模型，新能源识别率低

### ISSUE THREAD

**Issue by AliceYangs** [szad670401/HyperLPR#145]
![image](https://user-images.githubusercontent.com/43170504/53084648-3da45300-353c-11e9-8075-99a779c6d090.png)
该图片识别不出来，

linux下面的模型不是最新的吗？

**Comment by panda-lab** [comment]
参考新能源模型调用方法，#142

**Comment by AliceYangs** [comment]
> 参考新能源模型调用方法，#142

#142也是我提的，我回复的，是可以识别的，但识别率很低，比那个演示apk识别率低很多，比如上面那张图就没法识别。

**Comment by ZhangJiaLei123** [comment]
请问怎么把Linux下的模型转换到android下？Prj-Linux下就找到caffemodel和prototxt格式的文件，怎么转换成安卓能用的呢？

**Comment by panda-lab** [comment]
@ZhangJiaLei123  直接可以调用，用opencv android

**Comment by ZhangJiaLei123** [comment]
特别感谢您的回复，
再次麻烦请教一下，Prj_Linux下的模型怎么更新到安卓项目中？
以下是详细问题：
我已经成功运行了android项目，但是识别率没有pr样例app高，看readMe中说，可以将Prj_Linux下的模型复制到android中，但我再其文件夹下发现的模型文件，不知道该复制到哪？是AS项目中的某个文件夹还是直接复制到手机中。因为我在AS项目中没有找到类似可以被替换的资源，以下是资源截图![资源截图](https://raw.githubusercontent.com/ZhangJiaLei123/Picture-bed/master/TIM%E6%88%AA%E5%9B%BE20190305100416.jpg)

**Comment by lxhAndSmh** [comment]
@AliceYangs 你好，可以把你支持新能源识别的demo，push到你的github仓库吗，我在调试新能源车牌时，碰到了一些问题 #182 ，很困扰，感谢你的帮助
