### ISSUE TITLE
现在HyperLPRLite中是否还有精定位？

### ISSUE THREAD

**Issue by LongQIByte** [szad670401/HyperLPR#146]
这个项目很棒，我在学习该项目的时候看了这个[HyperLPR车牌识别技术算法之车牌精定位
](https://blog.csdn.net/Relocy/article/details/78705566)博客，它对项目中的精定位做了很详细的描述，但是在阅读运行Demo中的HyperLPRLite代码中没有发现精定位。请问在HyperLPRLite代码中只是用了神经网络去拟合边界吗？

**Comment by panda-lab** [comment]
原始代码中有精确定位，可以参考原始代码。O(∩_∩)O~

**Comment by LongQIByte** [comment]
@lsy17096535 谢谢您的解答，我想再问一下现在是不是不使用精确定位效果也可以。

**Comment by panda-lab** [comment]
是的
