### ISSUE TITLE
基于c++ windows的端到端识别

### ISSUE THREAD

**Issue by sayyoume** [szad670401/HyperLPR#149]
基于windows c++的端到端的识别 用的是opencv 345 编译出来没法运行。请问是因为opencv的版本问题吗?

cascade.detectMultiScale(processImage, platesRegions, 1.1, 3, cv::CASCADE_SCALE_IMAGE, minSize, maxSize); 这里直接返回了platesRegions获取的是大小为0，

**Comment by panda-lab** [comment]
没有检测到车牌，你看下图片载入是否正确，还有分类器的选择是否正确。

**Comment by sayyoume** [comment]
分类器用的是linux目录下的分类器。图片没问题
