### ISSUE TITLE
希望能将android代码更新到样例app的水准

### ISSUE THREAD

**Issue by ZhangJiaLei123** [szad670401/HyperLPR#150]
样例app能在我的android4.4的机型上顺利运行，此库中的项目编译后，在实体机上运行报错`E/cv::error(): OpenCV(3.4.2) Error: Unspecified error (FAILED: fs.is_open(). Can't open "/storage/emulated/0/pr/Segmentation.prototxt") in bool cv::dnn::ReadProtoFromTextFile(const char*, google::protobuf::Message*), file /build/3_4_pack-android/opencv/modules/dnn/src/caffe/caffe_io.cpp, line 1121`，十分苦恼，没有找到解决方案，特来求助

**Comment by panda-lab** [comment]
@ZhangJiaLei123  不好意思，我们把android重新整理一下，准确度是一样的，就是自己需要编译更改一下。
