### ISSUE TITLE
Python 3环境下无法运行成功

### ISSUE THREAD

**Issue by jerrychong25** [szad670401/HyperLPR#151]
大家好，

我根据[探索 Python + HyperLPR 进行车牌识别](https://www.jianshu.com/p/7ab673abeaae)的教程设置Python 3运行环境。

可是，到了第4步，Jupyter Notebook运行后并没有出现任何结果（一片空白），如下图：
![jupyter error](https://user-images.githubusercontent.com/15714095/53799972-a812b580-3f76-11e9-86de-ca94c247ace0.JPG)

然后我尝试在PowerShell运行此代码（位于test.py），但有错误出现，如下图：
![power shell error](https://user-images.githubusercontent.com/15714095/53800025-cbd5fb80-3f76-11e9-98ab-e77c3aa05d3c.JPG)

请问要设置些什么，才能运行成功呢？

谢谢！

**Comment by 2017TJM** [comment]
需要下载好opencv ,pip等包，需要修改相关的代码

**Comment by jerrychong25** [comment]
@2017TJM 你好，

我已经根据教程安装了opencv-python等包，如下：
![image](https://user-images.githubusercontent.com/15714095/54000759-b08c0b80-4183-11e9-8656-cb13dff52f25.png)

关于修改代码，请问是需要改哪里呢？因为教程没有给与任何说明。

谢谢。

**Comment by jerrychong25** [comment]
请问有任何消息吗？

谢谢！
