### ISSUE TITLE
How to retrain the Detector MobileNet-SSD

### ISSUE THREAD

**Issue by soufianesabiri** [szad670401/HyperLPR#152]
When I open the repo https://github.com/zeusees/Mobilenet-SSD-License-Plate-Detection I see `.prototxt` and `.caffemodel`, so I assume the developer used Caffe for training... But when I check the code of HyperLPR I see Keras... And when I check the file https://pan.baidu.com/s/11V0Pfx6jGNaBOOTqDSVK2Q I see the files `.pb` and `.pbtxt` whom are generated by retrain in tensorflow...

So what method did you use for training, Caffe, Keras or Tensorflow??? Also if you can give me a tutorial I will be very happy. Thanks!

**Comment by panda-lab** [comment]
you can refer https://blog.csdn.net/lsy17096535/article/details/78687728
