### ISSUE TITLE
AttributeError: module 'cv2' has no attribute 'CascadeClassifier'

### ISSUE THREAD

**Issue by willxian** [szad670401/HyperLPR#153]
e:\install\python3.5_64\lib\hyperlpr\detect.py in <module>
      5 
      6 
----> 7 watch_cascade = cv2.CascadeClassifier('./model/cascade.xml')
      8 
      9 

AttributeError: module 'cv2' has no attribute 'CascadeClassifier'

**Comment by panda-lab** [comment]
看一下opencv版本， 感觉是opencv安装的问题。查看cascade.xml路径是否正确。
