### ISSUE TITLE
Python3下Hyperlpr GUI无法启动直接报告内存错误

### ISSUE THREAD

**Issue by wangning316** [szad670401/HyperLPR#155]
Process finished with exit code -1073740791 (0xC0000409)
各位大佬请问是啥原因呀？
debug模式也是这样。。

**Comment by panda-lab** [comment]
这个还真的不好判断，你再调试一下，不好意思哈。。。

**Comment by janus1999** [comment]
我在python3下也是一样，调试的时候到这一句  res = np.array(model.predict(np.array([image]))[0])  ，执行predict的时候报错：
{ValueError}Tensor Tensor("activation_19/Softmax:0", shape=(?, 5), dtype=float32) is not an element of this graph.

**Comment by panda-lab** [comment]
@janus1999  尝试 :https://blog.csdn.net/donaldsy/article/details/95097024
