### ISSUE TITLE
android能不能获取车牌位置

### ISSUE THREAD

**Issue by ZhangJiaLei123** [szad670401/HyperLPR#157]
请问能不能返回车牌的识别位置，或将车牌区域单独扣出来？

**Comment by panda-lab** [comment]
可以啊，jni代码自己讲车牌位置返回即可。

**Comment by ZhangJiaLei123** [comment]
请问该如何操作？我再代码里面没有找到，cpp里也没有找到办法

**Comment by ZhangJiaLei123** [comment]
我试图获取车牌位置，但返回的却是负数，请问有更可靠的方法么？
![代码](https://github.com/ZhangJiaLei123/Picture-bed/blob/master/pr_c_%E8%8E%B7%E5%8F%96%E8%BD%A6%E7%89%8C%E4%BD%8D%E7%BD%AE.jpg?raw=true)

**Comment by 0830arthur** [comment]
"PlateRecognition.java" 中的這行代碼出錯 ===> System.loadLibrary("hyperlpr");
找不到 hyperlpr. 請問該如何取得這 Library??
