### ISSUE TITLE
linux系统中怎么使用这个框架呢？

### ISSUE THREAD

**Issue by boreas-l** [szad670401/HyperLPR#158]
没怎么用过github，有哪位大佬可以指导一下如何在linuxzhong使用这个框架吗？我的系统是ubuntu。谢谢了

**Comment by panda-lab** [comment]
可以采用python工程，也可以直接采用我们的linux-cpp代码。

**Comment by boreas-l** [comment]
> 可以采用python工程，也可以直接采用我们的linux-cpp代码。

我按readme中的指示编译了一下，结果虚拟机卡死了，这个框架的运行对配置有什么要求吗？谢谢了。

**Comment by panda-lab** [comment]
这个框架对机器的性能要求比较低，应该不会这样。你看下虚拟机的配置。

**Comment by boreas-l** [comment]
> 这个框架对机器的性能要求比较低，应该不会这样。你看下虚拟机的配置。

我虚拟机的配置是i5-4210U，双核，64G存储。配置是不是太差了？

**Comment by panda-lab** [comment]
@Phoenix-LXC 按理说这个配置运行时没问题的，估计跟虚拟机有关系。
