### ISSUE TITLE
VS2017 opencv401 编译出现未识别字符

### ISSUE THREAD

**Issue by Morph-3800** [szad670401/HyperLPR#161]
windows平台vs2017opencv4.01版本，在编译的时候CV_COMP_CORREL和CV_StsBadArg检测为为声名的标识符，请问是配置问题还是OpenCV的版本问题呢

**Comment by panda-lab** [comment]
应该是版本问题，用3.4.1 - 3.4.3 我们都测试过，没有问题。

**Comment by Morph-3800** [comment]
> 应该是版本问题，用3.4.1 - 3.4.3 我们都测试过，没有问题。

好的，我明天去试试3.4.1，谢谢大神

**Comment by Morph-3800** [comment]
> 应该是版本问题，用3.4.1 - 3.4.3 我们都测试过，没有问题。

大神我用3.4.1试了一下，未声明标识符的问题解决了，可是在编译的时候报了无法找到OpenCV_world330d.lib的错，我的电脑之前没有安装过任何版本的OpenCV，这里直接报找不到3.3.0版本的库的错，而且跑其他程序不会报这个错，请问这种问题有解决方案吗
