### ISSUE TITLE
hyperlpr原先对cascade级联分类器的训练样本里新能源和军车的训练样本是否不够

### ISSUE THREAD

**Issue by indulge216** [szad670401/HyperLPR#163]
hyperlpr原先对cascade级联分类器的训练样本里新能源和军车的训练样本是否不够，导致有时无法检测出新能源车牌（绿），军车（白）？

**Comment by panda-lab** [comment]
是的，这部分样本不是很多。

**Comment by indulge216** [comment]
我找了大概100张这些样本图片，能使识别的能力提高吗

> 是的，这部分样本不是很多。

**Comment by charlestamz** [comment]
100张不够，5000张差不多了
