### ISSUE TITLE
Android 运行奔溃 Can't open "...caffe_io.cpp

### ISSUE THREAD

**Issue by anan03** [szad670401/HyperLPR#165]
Android 运行奔溃 Can't open "...caffe_io.cpp
OpenCV error: Cannot load info library for OpenCV

cv::error(): OpenCV(3.4.2) Error: Unspecified error (FAILED: fs.is_open(). Can't open "/storage/emulated/0/pr/HorizonalFinemapping.prototxt") in bool cv::dnn::ReadProtoFromTextFile(const char*, google::protobuf::Message*), file /build/3_4_pack-android/opencv/modules/dnn/src/caffe/caffe_io.cpp, line 1121

**Comment by hu670014125** [comment]
这个问题是assets中没有训练模型导致无法读取，把Prj-Linux/lpr/model/下所有的文件复制到android项目assets中，在运行就正常了
