### ISSUE TITLE
Android源码 fail ?

### ISSUE THREAD

**Issue by 0830arthur** [szad670401/HyperLPR#172]
"PlateRecognition.java" 中的這行代碼出錯  ===> System.loadLibrary("hyperlpr"); 
找不到 hyperlpr. 請問該如何取得這 Library??

**Comment by hu670014125** [comment]
通过NDK编译后生成hyperlpr动态库

**Comment by 0830arthur** [comment]
> 通过NDK编译后生成hyperlpr动态库

對不起, 我是新手, 可以說的詳細一點嗎? 還是有相關資料?? 謝謝....

**Comment by hu670014125** [comment]
1.从Android的官方下载ndk，
2.下载Prj-Android项目
3.配置SDK和NDK的路径，在local.properties文件中设置。
如：
ndk.dir=/Users/xxxx/Documents/sdk/NDK/android-ndk-r16b
sdk.dir=/Users/xxxx/Documents/sdk
就可以正常编译了

**Comment by panda-lab** [comment]
@hu670014125 非常感谢。

**Comment by 0830arthur** [comment]
> ndk.dir=/Users/xxxx/Documents/sdk/NDK/android-ndk-r16b
> sdk.dir=/Users/xxxx/Documents/sdk
> 就可以正常编译了

可以正常编译   但是一樣執行到這行 code 時會出現錯誤, couldn't find "libhyperlpr.so".... 
  System.loadLibrary("hyperlpr");

**Comment by panda-lab** [comment]
@0830arthur  你把so手动拷贝到lib目录下

**Comment by 0830arthur** [comment]
> @0830arthur 你把so手动拷贝到lib目录下

專案裡找不到 "libhyperlpr.so" 這個檔案ㄚ....

**Comment by panda-lab** [comment]
@0830arthur 在你的编译目录里面，你好好找一下，搜索一下，以前我也遇到过这个问题。

**Comment by 0830arthur** [comment]
> @0830arthur 在你的编译目录里面，你好好找一下，搜索一下，以前我也遇到过这个问题。
搜索過, 沒有, 只有  "libopencv_java3.so".
