### ISSUE TITLE
Android 编译不通过

### ISSUE THREAD

**Issue by AimeeChen** [szad670401/HyperLPR#175]
编译环境：
Win7 64位
Android Studio 3.1.2
android-ndk-r14b

错误提示如下：
![image](https://user-images.githubusercontent.com/22937496/57673446-9d4b5f80-764e-11e9-8518-96501c55d3ff.png)

**Comment by AimeeChen** [comment]
已经解决这个问题了：
1）把android-sdk-windows\cmake\3.10.2.4988404删除
2）再在Android Studio 的SDK Manager里面下载CMake的3.6.4111459版本
3）再次编译就可以编译成功了

**Comment by panda-lab** [comment]
@AimeeChen  非常感谢，后面的小伙伴可以有一个参考了，记得采用segmentation-free.caffemodel模型测试哦。
