### ISSUE TITLE
运行demo.py报错AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by sxk000** [szad670401/HyperLPR#177]
运行demo.py报错AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by sxk000** [comment]
Traceback (most recent call last):
  File "demo.py", line 46, in <module>
    for pstr,confidence,rect in model.SimpleRecognizePlateByE2E(grr):
  File "/Users/kevinsun/Desktop/mycode/2019/04_car_HyperLPR/HyperLPRLite.py", line 148, in SimpleRecognizePlateByE2E
    images = self.detectPlateRough(image,image.shape[0],top_bottom_padding_rate=0.1)
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by panda-lab** [comment]
没有读取到图片

**Comment by sxk000** [comment]
我安装说明直接运行的demo.py 文件，还需要修改相关的代码吗？

**Comment by sxk000** [comment]
> 没有读取到图片
我安装说明直接运行的demo.py 文件，还需要修改相关的代码吗？

**Comment by truetone2022** [comment]
@sxk000 请问这个问题如何解决？

**Comment by sxk000** [comment]
> @sxk000 请问这个问题如何解决？

我后来也没有解决

**Comment by sxk000** [comment]
@hustpenghuan 我后来也没有解决
