### ISSUE TITLE
训练出来的model.h5，Android 端怎么引用？

### ISSUE THREAD

**Issue by AimeeChen** [szad670401/HyperLPR#179]

**Comment by panda-lab** [comment]
这个是keras模型，Android需要用caffe model

**Comment by AimeeChen** [comment]
@lsy17096535  你好，想问下你们做的caffe model是用caffe训练出来的么？我看网上有些是说可以将keras模型转成caffe模型

**Comment by panda-lab** [comment]
@AimeeChen 是的，有现成的代码可以参考，keras2caffe，你搜索一下。

**Comment by AimeeChen** [comment]
@lsy17096535 你好，使用”端到端(CTC)训练代码”训练出model.h5，然后转成caffe model，替换安卓下的SegmenationFree-Inception.caffemodel和SegmenationFree-Inception.prototxt，识别不出车牌。不知道你们有没有这样试过？
