### ISSUE TITLE
Win下C++版本无法识别8位新能源车牌

### ISSUE THREAD

**Issue by SalamanderEyes** [szad670401/HyperLPR#183]
看到之前的网友提到的关于新能源车牌识别的问题都是关于android版本的，想请问下在Win下运行的C++版本能否识别新能源车牌？该如何操作（也是需要采用端到端模型吗）？

**Comment by panda-lab** [comment]
如果想识别新能源，请采用linux下的代码，并加载segmentation-free.caffemodel模型。

**Comment by SalamanderEyes** [comment]
请问Linux下的C++代码可否迁移至Windows版本，使Win版本的C++代码可以识别新能源？

**Comment by panda-lab** [comment]
可以啊，直接用vs编译linux的代码即可

**Comment by SalamanderEyes** [comment]
用vs编译linux的代码已实现新能源车牌的识别，但会输出如下内容：
Attempting to upgrade batch norm layers using deprecated params: ../lpr/model/SegmentationFree.caffemodel
Successfully upgraded batch norm layers using deprecated params.
请问这是正常输出的吗

**Comment by panda-lab** [comment]
没问题，如果方便，可以给我们提交一个pr，帮我们更新一下win的代码。

**Comment by SalamanderEyes** [comment]
请问如何提交

**Comment by panda-lab** [comment]
github提交pull request，或者把代码发给contact@zeusee.com，注明作者，我们会在更细代码后说明，联系您。

**Comment by panda-lab** [comment]
感谢工程，已经提交，作者贡献在readme中进行了说明。
