### ISSUE TITLE
安卓项目里面assets下少文件了

### ISSUE THREAD

**Issue by wangchunfei** [szad670401/HyperLPR#184]
copyFilesFromAssets(this, assetPath, sdcardPath);
        String cascade_filename  =  sdcardPath
            + File.separator+"cascade.xml";
        String finemapping_prototxt  =  sdcardPath
                + File.separator+"HorizonalFinemapping.prototxt";
        String finemapping_caffemodel  =  sdcardPath
                + File.separator+"HorizonalFinemapping.caffemodel";
        String segmentation_prototxt =  sdcardPath
                + File.separator+"Segmentation.prototxt";
        String segmentation_caffemodel =  sdcardPath
                + File.separator+"Segmentation.caffemodel";
        String character_prototxt =  sdcardPath
                + File.separator+"CharacterRecognization.prototxt";
        String character_caffemodel=  sdcardPath
                + File.separator+"CharacterRecognization.caffemodel";
需要的文件有这么多，assets下只放了一个cascade.xml

**Comment by panda-lab** [comment]
这个需要自己放进去，我们都放在了linux/model下面，避免重复放置。
