### ISSUE TITLE
demo apk或者我集成到我的app,偶尔会出现一下问题，这个怎么解决

### ISSUE THREAD

**Issue by ldmgithub** [szad670401/HyperLPR#187]
#00 lr 00048f79 /system/lib/libc.so (__cxa_atexit+200) [armeabi-v7a]
--
2 java:
3 pr.platerecognization.PlateRecognition.finalize(PlateRecognition.java:71)
4 java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:229)
5 java.lang.Daemons$FinalizerDaemon.run(Daemons.java:207)
6 java.lang.Thread.run(Thread.java:818)

**Comment by panda-lab** [comment]
有可能跟你的Android手机存在不兼容，可以调试看一下，这个错误我们不好直接判断。

**Comment by ldmgithub** [comment]
使用demo也是一样，偶尔也会报这个错，用了两三台手机一样情况，我是频繁的开启识别之后，后台杀死app之后再打开，重复这样，当到达一个点后，就出现这个问题了

**Comment by panda-lab** [comment]
好的，如果可以固定复现，我们来解决这个问题。

**Comment by ldmgithub** [comment]
嗯，麻烦了，可以多测测，我直接用demo也会出现，但是嵌套到其他应用，因为其他应用比较大，导致回收什么的比较多，导致这个问题很容易出现，demo出现两次的情况下，我的应用会出现三四倍次数的
