### ISSUE TITLE
SIMPLE: Error configuring

### ISSUE THREAD

**Issue by farmercz** [szad670401/HyperLPR#188]
请问，这个安卓项目怎么能编译过去，gradle去掉 
externalNativeBuild {
        cmake {
            path 'CMakeLists.txt'
        }
    }
能编译过去，但是运行就couldn't find "libhyperlpr.so"。

加上如上那句就报SIMPLE: Error configuring，同时build下无cmake目录。

**Comment by panda-lab** [comment]
在你的工程build文件夹里面，好好找一下。
