### ISSUE TITLE
prj_win模型文件与代码不对应

### ISSUE THREAD

**Issue by gitcsw** [szad670401/HyperLPR#189]
readme里面内容与"../lpr/model/cascade.xml",
		"../lpr/model/HorizonalFinemapping.prototxt", "../lpr/model/HorizonalFinemapping.caffemodel",
		"../lpr/model/Segmentation.prototxt", "../lpr/model/Segmentation.caffemodel",
		"../lpr/model/CharacterRecognization.prototxt", "../lpr/model/CharacterRecognization.caffemodel",
		"../lpr/model/SegmentationFree.prototxt", "../lpr/model/SegmentationFree.caffemodel"
不符，且修改SegmenationFree-Inception.prototxt -> SegmenationFree.prototxt后仍运行失败：{msg="OpenCV(4.1.0) ...\\opencv\\modules\\dnn\\src\\caffe\\caffe_io.cpp:1121: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open \"../lpr/model/SegmentationFree.prototxt\" in function 'cv::dn... ...}

**Comment by lanybass** [comment]
怎么解决的？

**Comment by gitcsw** [comment]
修改代码为那个文件的名称即可，应该是他模型有固定格式命名。

**Comment by JorgeLiu** [comment]
啥意思？没看明白你这个是怎么改的，我也是报这个错

**Comment by dreamFinoa** [comment]
模型文件名是SegmenationFree-Inception.prototxt ，代码中的名称是SegmentationFree.prototxt，注意Segmentation单词中的t，模型文件名少了一个t

**Comment by WishYouANiceDay** [comment]
> 模型文件名是SegmenationFree-Inception.prototxt ，代码中的名称是SegmentationFree.prototxt，注意Segmentation单词中的t，模型文件名少了一个t

！！！！！一晚上都在纠结这个。。。抓狂了！谢谢啊大哥
