### ISSUE TITLE
识别准确率

### ISSUE THREAD

**Issue by Dearge** [szad670401/HyperLPR#191]
测试了一下模型的识别准确率，效果并不是很好，有的车牌对于前面的汉字识别不出来或者识别错误，不知道作者对这方面有优化的想法或者思路吗？

**Comment by panda-lab** [comment]
你采用的那个工程代码？可以尝试我们的segmentation-free.caffemodel 这个模型，配合linux代码。

**Comment by Dearge** [comment]
我采用的是工程目录下demo.py中提到的三个模型，其中识别模型是model/ocr_plate_all_gru.h5，感觉汉字识别错误的很多

**Comment by panda-lab** [comment]
采用linux代码对应的模型试试哈

**Comment by Dearge** [comment]
您好，想问一下model/ocr_plate_all_gru.h5这个模型的训练代码是端到端(多标签分类)训练代码还是端到端(CTC)训练代码?
