### ISSUE TITLE
Android 4.4报错 Unspecified error (FAILED: ReadProtoFromBinaryFile(param_file, param)

### ISSUE THREAD

**Issue by zxj522767** [szad670401/HyperLPR#193]
在运行Android示例demo的时候 在Android9.0的机器上可以正常运行 在Android4.4的机器上一运行就报这个错误

08-12 17:06:57.209 13099-13099/pr.platerecognization E/cv::error(): OpenCV(3.4.2) Error: Unspecified error (FAILED: ReadProtoFromBinaryFile(param_file, param). Failed to parse NetParameter file: /storage/emulated/0/pr/SegmenationFree-Inception.caffemodel) in void cv::dnn::ReadNetParamsFromBinaryFileOrDie(const char*, opencv_caffe::NetParameter*), file /build/3_4_pack-android/opencv/modules/dnn/src/caffe/caffe_io.cpp, line 1161
08-12 17:06:57.211 13099-13099/pr.platerecognization A/libc: Fatal signal 6 (SIGABRT) at 0x0000332b (code=-6), thread 13099 (terecognization)
08-12 17:06:57.211 13099-13099/pr.platerecognization A/libc: Send stop signal to pid:13099 in void debuggerd_signal_handler(int, siginfo_t*, void*)

**Comment by panda-lab** [comment]
把模型文件考进去

**Comment by zxj522767** [comment]
谢谢 问题解决了 ：
将Prj-Linux项目下model中的文件全部copy到Prj-Android中assets的pr目录下
