### ISSUE TITLE
AttributeError: module 'keras.backend' has no attribute 'set_image_dim_ordering'

### ISSUE THREAD

**Issue by thousmile** [szad670401/HyperLPR#198]
都按照你 博客上面装的但是报这个错误

========= RESTART: C:\Users\wangchenchen\Desktop\Jupyter\LPR\test.py =========
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\wangchenchen\Desktop\Jupyter\LPR\test.py", line 1, in <module>
    from hyperlpr import  pipline as  pp
  File "D:\development\python\Python36\lib\hyperlpr\pipline.py", line 5, in <module>
    from . import segmentation
  File "D:\development\python\Python36\lib\hyperlpr\segmentation.py", line 22, in <module>
    K.set_image_dim_ordering('tf')
AttributeError: module 'keras.backend' has no attribute 'set_image_dim_ordering'

![image](https://user-images.githubusercontent.com/28520524/66731201-b61fa180-ee88-11e9-9a8a-86e6d761ad29.png)

**Comment by happylin0x29a** [comment]
原因是因为kears 新版本没有这个方法了，可以通过K.set_img_data_format("channels_last")修改成功，但是后面还是会碰到错误，我还没有解决

**Comment by happylin0x29a** [comment]
keras 使用2.0.9就可解决

**Comment by bookman233** [comment]
使用：
pip install keras==2.0.8
可以解决这一问题

**Comment by AlanNewImage** [comment]
或者将对应代码改成K.set_img_data_format()
