### ISSUE TITLE
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

### ISSUE THREAD

**Issue by iamblue** [szad670401/HyperLPR#20]
Line 147:
https://github.com/zeusees/HyperLPR/blob/master/hyperlpr_py3/segmentation.py#L147

My Env: 
- python3 : 3.6.2

**Comment by bacy** [comment]
我也遇到相同的问题， python3.6.2

**Comment by wellfrog27** [comment]
python3.6.2
同样的情况

**Comment by szad670401** [comment]
HyperLPR是使用Python2开发的，py3的代码由@iamblue jas0nsh贡献

**Comment by bacy** [comment]
我修改了下，大概是py3里面不能隐式转换导致的，把传入的参数mid强转下就可以了，int(mid)这样

**Comment by moonyoung430** [comment]
@bacy 你好，我也是这个问题，但不是每张图片都会出现，你说强转的mid 是哪个东西？我没看懂，能解释一下吗？

**Comment by szad670401** [comment]
新的更新的可以通过pip一坚安装 支持python3
