### ISSUE TITLE
黄牌车第一次识别正确，纠正后就错了

### ISSUE THREAD

**Issue by liugt34** [szad670401/HyperLPR#205]
![image](https://user-images.githubusercontent.com/8056013/68845832-fdf34c00-0706-11ea-8e7e-295013f46b8f.png)

![image](https://user-images.githubusercontent.com/8056013/68845870-0fd4ef00-0707-11ea-94ca-239cced07225.png)

```
from hyperlpr import pipline as pp
import cv2

image = cv2.imread("car/4.png")
image, res = pp.SimpleRecognizePlate(image)
print("===================================================")
print(res)
```

**Comment by panda-lab** [comment]
这不是纠正，这是两种不同的算法给出的结果，参考上面的e2e结果即可。
