### ISSUE TITLE
c# 怎么调用这个动态库

### ISSUE THREAD

**Issue by SpringHgui** [szad670401/HyperLPR#208]

**Comment by panda-lab** [comment]
可以的 把C++代码编译成dll，然后用C#调用即可。

**Comment by SpringHgui** [comment]
怎么编译啊，c++没搞过，有没有编译好的，直接调用，最好是32位的

**Comment by SpringHgui** [comment]
生成没问题了，启动报错是什么问题

**Comment by SpringHgui** [comment]
![image](https://user-images.githubusercontent.com/22363718/69792626-eeddc500-1201-11ea-92fb-17a90c19f007.png)

**Comment by SpringHgui** [comment]
动态库编译好了，怎么调用呢
