### ISSUE TITLE
关于EasyPR数据集识别率

### ISSUE THREAD

**Issue by ContentAndMaterialPortrait** [szad670401/HyperLPR#21]
你好，我想问下作者的：
“识别率高,仅仅针对车牌ROI在EasyPR数据集上，0-error达到 95.2%, 1-error识别率达到 97.4% (指在定位成功后的车牌识别率)”
1、是在EasyPR的600张数据上测试的吗？
2、还有就是0-error是指车牌定位准确率95.2%吗，iou采用多少判定为定位准确呢？

**Comment by panda-lab** [comment]
@YouZengLi  多谢关注，针对你的问题：
1.在EasyPR提供数据集测试的，与EasyPR自己测试集一致；
2.0-error指字符全部识别正确，1-error指车牌字符识别错一位。
另外，这个结果是用python版本采用end-to-end模型得到，不是android版本或者其他版本，其他版本是我们一个简单的移植，给大家参考。
