### ISSUE TITLE
请问我想训练能够识别黄牌两行的话，要修改哪些东西，恳请提供教程 如果有的话 谢谢

### ISSUE THREAD

**Issue by ffllc** [szad670401/HyperLPR#210]
请问我想训练能够识别黄牌两行的话，要修改哪些东西，恳请提供教程 如果有的话 谢谢

**Comment by mattzhang1984** [comment]
黄色双层即将release 将会支持多种车牌

**Comment by AlanNewImage** [comment]
现在支持双层黄牌，试试v2分支下的python程序。将主函数中的DB置为true。欢迎测试后提出意见
