### ISSUE TITLE
prj-win opencv报错  Error: Assertion failed (ngroups > 0 && inpCn % ngroups == 0 && outCn % ngroups == 0)

### ISSUE THREAD

**Issue by JorgeLiu** [szad670401/HyperLPR#211]
OpenCV(4.1.2) Error: Assertion failed (ngroups > 0 && inpCn % ngroups == 0 && outCn % ngroups == 0) in cv::dnn::ConvolutionLayerImpl::getMemoryShapes, file C:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\layers\convolution_layer.cpp, line 311

**Comment by AlanNewImage** [comment]
调试断在哪里截图看下？

**Comment by AlanNewImage** [comment]
升级下opencv 到3.4.3
