### ISSUE TITLE
识别耗时接近2s

### ISSUE THREAD

**Issue by Suntester** [szad670401/HyperLPR#212]
配置
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
2.3 GHz Intel Core i5
样例代码如下，耗时接近2000ms。官方是100ms，请问哪里出了问题

#导入包
from hyperlpr import *
#导入OpenCV库
import cv2
import time
#读入图片
image = cv2.imread("demo.jpg")
#识别结果
start = time.time()
print(HyperLPR_plate_recognition(image))
print(time.time() - start)

**Comment by panda-lab** [comment]
多大分辨率的图片？

**Comment by Suntester** [comment]
> 多大分辨率的图片？

图片大小为361 * 640
如果代码在一个脚本里面执行两遍，第二遍耗时就很正常，只有30ms。

from hyperlpr import *
import cv2
import time

start = time.time()
image = cv2.imread("test.jpeg")
print(HyperLPR_plate_recognition(image))
print(time.time() - start)
### 耗时1980ms

start = time.time()
image = cv2.imread("test.jpeg")
print(HyperLPR_plate_recognition(image))
print(time.time() - start)
### 耗时30ms

**Comment by panda-lab** [comment]
第一次需要对深度学习框架启动，称为 warming up ，这个过程比较耗时。
