### ISSUE TITLE
module 'cv2' has no attribute 'estimateRigidTransform'

### ISSUE THREAD

**Issue by YuboW0** [szad670401/HyperLPR#222]
estimateRigidTransform 替换为了 estimateAffinePartial2D

**Comment by panda-lab** [comment]
好的，在哪个版本开始替换的？

**Comment by YuboW0** [comment]
我现在用的4.1.2没记错的话是opencv 4开始就换掉了

**Comment by panda-lab** [comment]
好的，高版本我们适配一下。谢谢啦。

**Comment by YuboW0** [comment]
好的谢谢

**Comment by YuboW0** [comment]
estimateAffinePartial2D返回一个元组然后第0位对应的原来estimateRigidTransform的返回值
https://docs.opencv.org/master/d9/d0c/group__calib3d.html#gad767faff73e9cbd8b9d92b955b50062d

231应该改成
mat_ = cv2.estimateAffinePartial2D(org_pts, target_pts, True)[0]

**Comment by kchbpy** [comment]
pip install opencv-python==3.4.9.31

**Comment by YuboW0** [comment]
https://docs.opencv.org/master/d9/d0c/group__calib3d.html#gad767faff73e9cbd8b9d92b955b50062d
