### ISSUE TITLE
无法处理具有一定倾斜角度的车牌

### ISSUE THREAD

**Issue by JiangTianxing** [szad670401/HyperLPR#224]
当图片中的车牌具有一定倾斜角度的时候，图片预处理后车牌块可能就不近似于长方形了，这时区域可能回搜索不到，针对这个问题，能不能进行系列优化了？

**Comment by panda-lab** [comment]
采用我们的v2版本

**Comment by lizhaokun** [comment]
你好，我使用了v2版本，运行demo的时候还是无法检测出来结果，您在test_image文件夹中提供的test.jpg这个图片就检测不出结果

**Comment by lizhaokun** [comment]
> 采用我们的v2版本
您好，我使用了v2版本的python代码，运行demo的时候还是无法检测出来结果，您在test_image文件夹中提供的test.jpg这个图片就检测不出结果

**Comment by AlanNewImage** [comment]
采用v2分支下的win版和python版本
