### ISSUE TITLE
android版编译打包 正常，运行  就崩

### ISSUE THREAD

**Issue by huangjinhao** [szad670401/HyperLPR#227]
E/cv::error(): OpenCV(3.4.2) Error: Unspecified error (FAILED: fs.is_open(). Can't open "/storage/emulated/0/pr/HorizonalFinemapping.prototxt") in bool cv::dnn::ReadProtoFromTextFile(const char*, google::protobuf::Message*), file /build/3_4_pack-android/opencv/modules/dnn/src/caffe/caffe_io.cpp, line 1121

**Comment by huangjinhao** [comment]
加上旧版assets里面的文件

**Comment by yuxingfafu** [comment]
加上旧版assets里面的文件
--这个是哪里呀？

**Comment by panda-lab** [comment]
@yuxingfafu Prj-linux /model目录下面

**Comment by yuxingfafu** [comment]
谢谢，老铁，请教下你搞过港澳台的车牌么？怎么训练接入知道的不？
