### ISSUE TITLE
运行报错：cannot import name 'pipline' from 'hyperlpr'

### ISSUE THREAD

**Issue by jv163** [szad670401/HyperLPR#229]
运行代码：from hyperlpr import  pipline as  pp
import cv2
# 自行修改文件名
image = cv2.imread("./car/1.jpg")
image,res  = pp.SimpleRecognizePlate(image)
print(res)

详细报错：
ImportError                               Traceback (most recent call last)
<ipython-input-4-d25081235a13> in <module>
----> 1 from hyperlpr import  pipline as  pp
      2 import cv2
      3 # 自行修改文件名
      4 image = cv2.imread("./car/1.jpg")
      5 res  = pp.SimpleRecognizePlate(image)

ImportError: cannot import name 'pipline' from 'hyperlpr' (c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\hyperlpr\__init__.py)

**Comment by AlanNewImage** [comment]
使用python3的话应该从hyperlpr_py3 import pipline
