### ISSUE TITLE
请问能否识别同意图片中多辆车的车牌？

### ISSUE THREAD

**Issue by moonyoung430** [szad670401/HyperLPR#23]
您好！
        首先非常感谢你们的贡献，这份源码对我的学习有很大的帮助！
        我利用python按照说明中进行测试时发现，在文件夹dataset中提供的图片24.jpg中有两辆以上车牌可以进行辨识，但是识别结果只有中间一辆车，请问SimpleRecognizePlate这个方法只能识别一辆车吗？或者还有别的方法可以同时识别的？
         最后，我刚下载源码进行测试，对于结果已经非常激动了，还没来得及仔细研究原理，另外在readme中附带的博客地址已经失效，不知是否有更新~~~
         以上，致谢！

**Comment by moonyoung430** [comment]
![image](https://user-images.githubusercontent.com/31330980/34402009-ef212c46-ebd9-11e7-8b99-e49852207e44.png)
我观察res中有几个车牌，但是image中只有一个被框出来了

**Comment by szad670401** [comment]
是可以识别多辆车的车牌的. 这张图片我测试过可以识别，查看你参数是否配置准确
