### ISSUE TITLE
当前代码和Python依赖的最新版本不兼容

### ISSUE THREAD

**Issue by wushaobo** [szad670401/HyperLPR#230]
例如 Keras 2.3.1 版本已将 
`K.set_image_dim_ordering('tf')` 变为了 `K.set_image_data_format('channels_last')`

我理解维护代码以适应新版本依赖需要花些时间，那么可否
仅更新当前代码适配的Python依赖版本列表到Readme，或用 pip freeze 到 requirements.txt中？

**Comment by wushaobo** [comment]
哪位跑起来了，请pip freeze贴一份列表上来吧！ 感谢

**Comment by openchao** [comment]
> 例如 Keras 2.3.1 版本已将
> `K.set_image_dim_ordering('tf')` 变为了 `K.set_image_data_format('channels_last')`
> 
> 我理解维护代码以适应新版本依赖需要花些时间，那么可否
> 仅更新当前代码适配的Python依赖版本列表到Readme，或用 pip freeze 到 requirements.txt中？

请问您有没有跑起来！detect.py一直提示我object() takes no parameters

**Comment by openchao** [comment]
> 哪位跑起来了，请pip freeze贴一份列表上来吧！ 感谢

我们要不加个QQ交流一下吧！
Q：1319609405

**Comment by AlanNewImage** [comment]
近期会更新
