### ISSUE TITLE
在linux下识别速度不如安卓的

### ISSUE THREAD

**Issue by YuGongCharley** [szad670401/HyperLPR#232]
我看Android的demo显示识别只需要一百毫秒左右，可是linux i7 32g内存下就要到一秒左右，这感觉不太对呀

**Comment by YuGongCharley** [comment]
android是在mate30 pro上跑的readme里链接的demo

**Comment by panda-lab** [comment]
@YuGongCharley  Android识别是因为图像会进行resize，linux 是在原始图像上做的检测和识别。

**Comment by YuGongCharley** [comment]
@lsy17096535 resize后还是在1秒左右

**Comment by YuGongCharley** [comment]
@lsy17096535 您好，我在安卓上分辨率调节为1倍耗时218ms linux下运行TEST_PIPLINE耗时1026ms，是相同图片，图片内有三个车牌，而且不管是黄牌、蓝牌还是新能源牌getPlateType()获取到的结果都是4293818。我github现在传不上图片，运行结果截图上传不了 见谅

**Comment by panda-lab** [comment]
@YuGongCharley 我们测试一下，看一下是不是linux的实现有问题，另外，linux的opencv dnn对识别速度也有影响，你看你编译opencv的时候是不是开启了加速选项。

**Comment by YuGongCharley** [comment]
@lsy17096535 我编译的时候应该没改选项，我也检查一下，麻烦您了

**Comment by YuGongCharley** [comment]
@lsy17096535 opencv是3.4.6，cmake时dnn相关的BUILD_opencv_dnn和OPENCV_DNN_OPENCL是开了的，opencv_dnn_PERF_CAFFE和opencv_dnn_PERF_CLCAFFE没开

**Comment by YuGongCharley** [comment]
@lsy17096535 opencv重新编译了一下，重点看了下dnn的选项，现在不做resize高速监控图片三张车牌耗时在200ms以内，之前编译可能没选上dnn，是我疏忽了，不好意思

更正下，因为我之前测试只运行了一次，看了之前close的issue：https://github.com/zeusees/HyperLPR/issues/212 猜测可能是第一次框架warming up的原因，之后测试连续进行三次识别，耗时除了第一次在一秒以上外，其余两次均在100ms以下：
time:1080ms
time1:98ms
time2:76ms
之前猜测原因可能是dnn编译的问题，因为我之前编译opencv是默认选项；但是我觉得更大的可能是warming up导致的，因为我最开始测试时每次只测试一张图，显示的耗时肯定高。
希望作者可以在readme里说明一下，因为耗时的问题我看issue里也有人提到过，也避免之后有不了解的朋友碰到这个问题，谢谢
