### ISSUE TITLE
python3项目问题

### ISSUE THREAD

**Issue by openchao** [szad670401/HyperLPR#241]
上传的python2和3的项目是不是都没完全弄好。为啥我运行不了这个项目。

**Comment by ghost** [comment]
是不是这个错误?
AttributeError: 'module' object has no attribute 'estimateRigidTransform'
这个错误是因为你的opencv-python版本过高.
pip3 install opencv-python==3.4.9.31
用这个安装低版本的.

**Comment by Panruihua** [comment]
感谢感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"nccer"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 晚上11:57
收件人:&nbsp;"zeusees/HyperLPR"<HyperLPR@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [zeusees/HyperLPR] python3项目问题 (#241)





 
是不是这个错误?
 AttributeError: 'module' object has no attribute 'estimateRigidTransform'
 这个错误是因为你的opencv-python版本过高.
 pip3 install opencv-python==3.4.9.31
 用这个安装低版本的.

**Comment by openchao** [comment]
> 是不是这个错误?
> AttributeError: 'module' object has no attribute 'estimateRigidTransform'
> 这个错误是因为你的opencv-python版本过高.
> pip3 install opencv-python==3.4.9.31
> 用这个安装低版本的.

Traceback (most recent call last):
  File "D:/procedure/HyperLPR/hyperlpr_py3/detect.py", line 4, in <module>
    watch_cascade = cv2.CascadeClassifier('../model/cascade.xml')
TypeError: object() takes no parameters

**Comment by openchao** [comment]
那个文件是主文件，我运行那个文件会出结果。
ImportError: cannot import name 'e2e'
这个问题是怎么回事？

**Comment by AlanNewImage** [comment]
使用hyperlpr_py3或者hyperlpr这俩个，需要你再主目录下写一个demo文件来调用各自目录下的pipline.py里的函数。
这里很快会更新。

**Comment by little7Li** [comment]
因为你的 opencv 版本过高了，没有 estimateRigidTransform 这个函数；如果你不想降opencv 版本，只需要改一行代码就可以，把 hyperlpr.py line 231 
`# mat_ = cv2.estimateRigidTransform(org_pts, target_pts, True)`
     改为   `mat_, _ = cv2.estimateAffine2D(org_pts, target_pts)`
就可以正常使用了
