### ISSUE TITLE
Demo中图片的格式rgb或bgr

### ISSUE THREAD

**Issue by zye1996** [szad670401/HyperLPR#242]
在demo中用cv2.imread()读取图片为bgr格式。在推断detectoin阶段用了语句
```image_gray = cv2.cvtColor(image_color_cropped,cv2.COLOR_RGB2GRAY)```
这里的RGB2GRAY是否应该为BRG2GRAY?
之后的finetune模型和ocr模型是否是基于rgb的数据集训练的还是使用了bgr呢？我在运行的时候默认rgb和gbr还是能够正确识别车牌， 这样混用通道是否会带来很大的误差？

**Comment by panda-lab** [comment]
多谢提醒，我们看一下这个问题，是否存在格式转化错误，如果方便，您也帮忙看一下，多谢。

**Comment by AlanNewImage** [comment]
cvtcolor的位置应该为BGR2GRAY
finetune和OCR部分应该是BGR的顺序
