### ISSUE TITLE
name 'HyperLPR_plate_recognition' is not defined

### ISSUE THREAD

**Issue by stq054188** [szad670401/HyperLPR#246]
按照python安装方法安装hyperlpr， 然后运行dmeo，报错了，，，是什么原因@zeusees
`#导入包
from hyperlpr import *

#导入OpenCV库
import cv2

#读入图片
image = cv2.imread("1.jpg")

#识别结果
print(HyperLPR_plate_recognition(image))`

报错：
Traceback (most recent call last):
  File "C:/Users/xxx/Desktop/Test/TestLPR.py", line 8, in <module>
    print(HyperLPR_plate_recognition(image))
NameError: name 'HyperLPR_plate_recognition' is not defined

**Comment by KangJunRong** [comment]
我也是一样的报错，安装在centos服务器上，求解

**Comment by AlanNewImage** [comment]
建议clone代码测试

**Comment by KangJunRong** [comment]
@stq054188 你是不是装了0.0.1版本的HyrerLPR啊，0.0.1的不是 HyperLPR_plate_recognition 这个方法名的， 0.0.1版本的是 HyperLPR_PlateRecogntion 这个方法名

**Comment by wwzh2015** [comment]
> @stq054188 你是不是装了0.0.1版本的HyrerLPR啊，0.0.1的不是 HyperLPR_plate_recognition 这个方法名的， 0.0.1版本的是 HyperLPR_PlateRecogntion 这个方法名

0.01和0.02都报错

**Comment by Huuush** [comment]
> 按照python安装方法安装hyperlpr， 然后运行dmeo，报错了，，，是什么原因@zeusees
> `#导入包
> from hyperlpr import *
> 
> #导入OpenCV库
> import cv2
> 
> #读入图片
> image = cv2.imread("1.jpg")
> 
> #识别结果
> print(HyperLPR_plate_recognition(image))`
> 
> 报错：
> Traceback (most recent call last):
> File "C:/Users/xxx/Desktop/Test/TestLPR.py", line 8, in
> print(HyperLPR_plate_recognition(image))
> NameError: name 'HyperLPR_plate_recognition' is not defined

可能是opencv版本太高了

**Comment by stq054188** [comment]
已解决

**Comment by Lie-huo** [comment]
请问解决了吗，我也是这样的问题

**Comment by Jinkham** [comment]
@Lie-huo  采用opencv 3.4.3

**Comment by Lie-huo** [comment]
好的，谢谢，可以了。我是pip install hyperlpr安装的，在图片中有多个车牌，但是只能识别出一个，这是什么原因呢？
