### ISSUE TITLE
关于检测率与识别率

### ISSUE THREAD

**Issue by cuicuizhang1989** [szad670401/HyperLPR#25]
采用HyperLPR和easypr 相同的测试集（easypr）提供的general_test 文件夹里面的图片测试，发现HyperLPR字符分割和识别率较低，而easyppr 较高似乎与readme说明的不一致，不知道是不是有什么细节参数之类的需要调整呢？

**Comment by panda-lab** [comment]
@cuicuizhang1989  配置python采用端到端模型再跑一下，这个数据没有问题，你可以到群里把错误图片发出来。

**Comment by cuicuizhang1989** [comment]
@lsy17096535 好的 确实是python 跑出来感觉不对 ，刚试了试win 似乎比python效果好

**Comment by panda-lab** [comment]
python 的效果是最新的模型 应该是最好的  你再配置一下试试

**Comment by xiaosi2017** [comment]
@lsy17096535 The qq group rejects getting in, why?

**Comment by panda-lab** [comment]
746123554
