### ISSUE TITLE
hyperlprV2   ImportError: cannot import name pipline

### ISSUE THREAD

**Issue by yuanzhenjie** [szad670401/HyperLPR#250]
hyperlprV2版本中，安装hyperlpr后。找不到pipline

`
(hyperlprv2) [root@dl-gpu hyperlprV2]# pip show hyperlpr
>>>DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Name: hyperlpr
Version: 0.0.2
Summary: A general small license plate recognition framework
Home-page: https://github.com/zeusees/HyperLPR
Author: Jack Yu
Author-email: jack-yu-business@foxmail.com
License: UNKNOWN
Location: /data/software/anaconda3/envs/hyperlprv2/lib/python2.7/site-packages
Requires: opencv-python
Required-by: 
`

`(hyperlprv2) [root@dl-gpu hyperlprV2]# python
Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 21:00:58) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import hyperlpr
>>> from hyperlpr import pipline
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name pipline
>>> hyperlprV2   ImportError: cannot import name pipline
KeyboardInterrupt`

**Comment by chessxu** [comment]
I also meet the question.Have you solved it?

**Comment by chessxu** [comment]
I had sovled this question.You could make numpy's version as 1.16.0,which will worked.
