### ISSUE TITLE
ssd_detection 输出异常

### ISSUE THREAD

**Issue by LoongWynn** [szad670401/HyperLPR#252]
## 版本
* Name: opencv-python Version: 3.4.2.16
* Name: hyperlpr Version: 0.0.2
## 问题描述
使用[一键安装](https://github.com/zeusees/HyperLPR#%E4%B8%80%E9%94%AE%E5%AE%89%E8%A3%85)方法部署的应用，对于任何图片返回空结果列表
## 发现问题
经检查在执行`helperlpr.py`文件54行时，ssd_detection.forward方法输出结果值域在[0,0.1] 之间，导致后续判断`score>0.5`时结果均为false，导致返回空列表
``` py
        print(im_tensor.shape)
        cropped_images = []
        cvOut = self.ssd_detection.forward()
        for detection in cvOut[0, 0, :, :]:
            score = float(detection[2])*10
            print(score)
            if score > 0.5:
                x1 = int(detection[3] * cols)
```
## 临时解决方案
在56行后添加`*10`
## 错误和改正错误后截图
![图片](https://user-images.githubusercontent.com/24761242/81471426-a05a3b00-9223-11ea-9542-878b0f7356c9.png)

**Comment by AlanNewImage** [comment]
建议贴出有问题的图片。方便复现

**Comment by LoongWynn** [comment]
> 建议贴出有问题的图片。方便复现

是普遍现象，可以用网络上的车牌图片试一试，都这样

**Comment by AlanNewImage** [comment]
根据你的描述应该是没有定位到车牌。
问题没有复现。

**Comment by Sh-Zh-7** [comment]
我也出现了这种现象，后来我把opencv-python升级到3.x的最高版本就行了。
建议讲requirements.txt里的opencv-python和opencv-contrib-python的版本号都提高为3.4.9.33
