### ISSUE TITLE
ssd_detection 重复调用异常

### ISSUE THREAD

**Issue by LoongWynn** [szad670401/HyperLPR#253]
## 版本
* Name: opencv-python Version: 3.4.2.16
* Name: hyperlpr Version: 0.0.2
## 问题描述
使用[一键安装](https://github.com/zeusees/HyperLPR#%E4%B8%80%E9%94%AE%E5%AE%89%E8%A3%85)方法部署的应用，针对 https://github.com/zeusees/HyperLPR/issues/252 方法修正后，在重复调用该函数以执行多次识别时，车牌定位函数结果异常（给出-inf）
## 发现问题
仅在初始化函数时调用了`cv2.dnn.readNetFromCaffe(*self.mini_ssd_path)`，之后调用之前权重未改变继续计算

## 临时解决方案
在调用`detect_ssd(self, im):`方法时重新赋值

**Comment by AlanNewImage** [comment]
参考https://github.com/zeusees/HyperLPR/blob/d1709cdfc3d7caf4aaa41efc68821f181da9ef26/hyperlpr_pip_pkg/hyperlpr/__init__.py#L7
文件中的调用方法。
