### ISSUE TITLE
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor请问这个你后来是怎么解决的呀

### ISSUE THREAD

**Issue by nana0127** [szad670401/HyperLPR#257]
请问OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor这个您是怎么解决的呀

_Originally posted by @gmg137 in https://github.com/zeusees/HyperLPR/issues/105#issuecomment-427716121_

**Comment by AlanNewImage** [comment]
1.升级opencv到3.4.3.18.
2.确认下cvtcolor送进去的图像是不是三通道的
