### ISSUE TITLE
Master & V2

### ISSUE THREAD

**Issue by ahuo002** [szad670401/HyperLPR#263]
测试后，发现 Master 的普通车牌识别效果比 V2好；
但是master 不支持 双黄；
V2 的双黄和单牌，只能2选一？
想测试Python版的，无奈环境装不全，timeout...
想知道 master 与 V2 的关系？看时间， V2比较新？
期待回复，Thanks♪(･ω･)ﾉ

**Comment by AlanNewImage** [comment]
V2是端到端的版本，检测是ssd，车牌矫正和识别部分全是网络实现，更简洁，只依赖opencv。V2的双层车牌和单层车牌只能2选一
master的车牌定位是cascade，矫正是图像加网络，识别分基于分割和端到端两种，依赖opencv和keras

**Comment by wongts44** [comment]
> V2是端到端的版本，检测是ssd，车牌矫正和识别部分全是网络实现，更简洁，只依赖opencv。V2的双层车牌和单层车牌只能2选一
> master的车牌定位是cascade，矫正是图像加网络，识别分基于分割和端到端两种，依赖opencv和keras

麻烦请问这个V2版本的链接是？我没有找到设置DB参数的代码
