### ISSUE TITLE
这个黑牌识别成了蓝牌

### ISSUE THREAD

**Issue by dotfeng** [szad670401/HyperLPR#273]
![u=2670820303,2880960355 fm=26 gp=0](https://user-images.githubusercontent.com/1728934/87216937-c95b9100-c376-11ea-9469-46fafa37d1fe.jpg)

**Comment by Jinkham** [comment]
黑牌的判断做的不好，夜晚的蓝牌也容易当成黑牌，我们想办法完善。

**Comment by netdrop-sys** [comment]
黑牌的判断做的不好，夜晚的蓝牌也容易当成黑牌，我们想办法完善。
