### ISSUE TITLE
windows下的端到端C++版本可以考虑用这个项目

### ISSUE THREAD

**Issue by piaobuliao** [szad670401/HyperLPR#29]
https://github.com/dlunion/CaffeLSTM-OCR

**Comment by mmchen88** [comment]
请问用这个项目训练车牌收敛了么？timestep设置的多少？

**Comment by piaobuliao** [comment]
@mmchen88 你说得是CaffeLSTM-OCR？ 我没搞过车牌，一行最多20个的端到端的汉字是可以收敛的，车牌应该也没问题的

**Comment by mmchen88** [comment]
是的，我试了CaffeLSTM-OCR。用作者给出的验证码训练收敛了，但是用车牌训练，没几步Loss就无穷大了。我尝试将timestep改为26，dropout_ratio调低都不行。

**Comment by piaobuliao** [comment]
@mmchen88  你模型结构要改一下吧，直接用原来估计效果不一定好

**Comment by szad670401** [comment]
验证码，车牌这类短期依赖问题不一定要用rnn，计算复杂还不好并行。
