### ISSUE TITLE
带UI界面的可执行文件无法运行

### ISSUE THREAD

**Issue by heartfulsong** [szad670401/HyperLPR#30]
我的系统是x64的Windows10，请问为什么无法运行编译好的带UI界面的可执行文件？

**Comment by panda-lab** [comment]
@heartfulsong  https://pan.baidu.com/s/1cNWpK6 这里有源码，自己编译一下吧

**Comment by heartfulsong** [comment]
非常感谢，我试试。


Sent from Meizu PRO 6 Plus

-------- Original message --------
Sender: syan <notifications@github.com>
Time: Tue 1/23 10:36
To: zeusees/HyperLPR <HyperLPR@noreply.github.com>
Cc: heartfulsong <15256944669@163.com>,Mention <mention@noreply.github.com>
 Subject: Re: [zeusees/HyperLPR] 带UI界面的可执行文件无法运行 (#30)
