### ISSUE TITLE
hyperlor.py的231行，estimateRigidTransform函数已被CV2废弃

### ISSUE THREAD

**Issue by SamCheng0717** [szad670401/HyperLPR#318]
希望作者大大可以修复该问题

**Comment by zhemejinnameyuan** [comment]
mat_ = cv2.estimateRigidTransform(org_pts, target_pts, True)

        dsize = (int(120 * scale), int(48 * scale))

        warped = cv2.warpAffine(image, mat_, dsize)


替换为下面,可以解决问题:



        mat_ = cv2.estimateAffine2D(org_pts, target_pts)

        dsize = (int(120 * scale), int(48 * scale))

        warped = cv2.warpAffine(image, mat_[0], dsize)

**Comment by liyan110120999** [comment]
我也遇到这个问题，该怎么改代码呢？pip 直接安装的

**Comment by qianxiaoer** [comment]
哈罗，邮件收到了，我会尽快查看，回复，谢谢！

**Comment by tunmx** [comment]
当前的版本已经不会出现该问题
```bash
python -m pip install hyperlpr3
```
详见readme
