### ISSUE TITLE
可以支持 arm64-v8a 吗

### ISSUE THREAD

**Issue by lxhAndSmh** [szad670401/HyperLPR#328]
你好，Android 的项目示例，现在只支持 armeabi-v7a，能支持一下 arm64-v8a 吗，谢谢

**Comment by qianxiaoer** [comment]
哈罗，邮件收到了，我会尽快查看，回复，谢谢！

**Comment by lxhAndSmh** [comment]
你好，有进展吗，辛苦了，谢谢！

**Comment by tunmx** [comment]
您好 目前已支持arm64-v8a
