### ISSUE TITLE
Master python3版本无法识别双行黄牌问题

### ISSUE THREAD

**Issue by liuliaocheng** [szad670401/HyperLPR#331]
您好，Master python3版本是无法识别双行黄牌吗，谢谢

**Comment by we0091234** [comment]
> 您好，Master python3版本是无法识别双行黄牌吗，谢谢
https://github.com/we0091234/Chinese_license_plate_detection_recognition
这个可以识别双行黄牌

**Comment by tunmx** [comment]
当前master已经支持双层黄牌
