### ISSUE TITLE
在Python上运行快速上手时，识别不出结果

### ISSUE THREAD

**Issue by wuyuekaixin** [szad670401/HyperLPR#340]
![image](https://user-images.githubusercontent.com/107248277/173034431-22fdf32a-abfc-4555-884a-506bb79fb47d.png)

![image](https://user-images.githubusercontent.com/107248277/173034029-a4841778-4839-49ff-9fae-0b371147602a.png)
在Python上运行快速上手时，识别不出结果，换张图后出现了报错。我看到有issue里回答了如何改代码才能不报错，但是我不知道应该去哪里改。下下来的文件是一个个分开的，我不知道从哪里找这个第231行代码。有没有大佬能帮帮忙（T ^ T）

**Comment by tunmx** [comment]
#318 尝试新版
