### ISSUE TITLE
Android 代码和演示版本不对

### ISSUE THREAD

**Issue by guhao0803** [szad670401/HyperLPR#343]
请问master分支上的Android 代码运行起来和演示的APP不一致是什么问题，或者说最新的代码是哪个分支的？

**Comment by Fujimiya-Asuka** [comment]
演示版APP里面识别模型不一样的。要交钱才能用吧

**Comment by yangkezun** [comment]
> 请问master分支上的Android 代码运行起来和演示的APP不一致是什么问题，或者说最新的代码是哪个分支的？

是不一样，模型版本要高一些

**Comment by tunmx** [comment]
当前项目版本已更新，master分支上的工程与android示例工程代码已经同步，我们提供了两种使用android-sdk的方式：
1. 从源工程编译安卓动态链接库后，拉取SDK工程：[https://github.com/HyperInspire/hyperlpr3-android-sdk](https://github.com/HyperInspire/hyperlpr3-android-sdk)，将动态库放进sdk工程中，编译安卓工程即可使用
2. 从jitpack中引入android-sdk的包：
```
allprojects {
    repositories {
        ...
        maven { url 'https://jitpack.io' }
    }
}

dependencies {
    implementation 'com.github.HyperInspire:hyperlpr3-android-sdk:1.0.3'
}
```
可参考工程：[Prj-Android](https://github.com/szad670401/HyperLPR/tree/master/Prj-Android)

以上内容详见[README](https://github.com/szad670401/HyperLPR/blob/master/README_CH.md)
