### ISSUE TITLE
如何识别一张图片里面的多张车牌

### ISSUE THREAD

**Issue by YUHANG-Ma** [szad670401/HyperLPR#346]
请问如何识别一张图片的多张车牌呢?我输入了一张含有三辆车的图片，但是结果只输出了一张车牌。

**Comment by we0091234** [comment]
有图片吗

**Comment by we0091234** [comment]
> 请问如何识别一张图片的多张车牌呢?我输入了一张含有三辆车的图片，但是结果只输出了一张车牌。

https://github.com/we0091234/Chinese_license_plate_detection_recognition  这个repo可以

**Comment by kaikaifight** [comment]
pip install hyperlpr==0.0.2版本, 在hyperlpr.py的65行, 即detect_ssd方法的return缩进错误, return应该放在for循环外面, 手动改以下就好了.

**Comment by tunmx** [comment]
您好，可以尝试拉取最新版的工程进行测试，已支持多个车牌的识别
