### ISSUE TITLE
first run catcher method it download unknown file from the web

### ISSUE THREAD

**Issue by tonyshare** [szad670401/HyperLPR#361]
After install `HyperLPR` I run the sample code as follows

```
import cv2
import hyperlpr3 as lpr3

# Instantiate object
catcher = lpr3.LicensePlateCatcher()
# load image
image = cv2.imread("src/car.jpg")
# print result
print(catcher(image))
```

the result turn to be right, but it download something from website as follows:
`Pull: 100%|████████████████████████████████████████████████| 11.9M/11.9M`

and then it print the correct answer, i run the previous code again it don't download nothing anymore.

what things did the program download from the internet, and which website

**Comment by tunmx** [comment]
hi, if you use hyperlpr3 for the first time, it will automatically download some static resource files needed to use the algorithm from the remote repository and store them in your user directory. The download will only be performed once, unless you manually delete the files.

**Comment by tonyshare** [comment]
@tunmx which file and place did it download to?

**Comment by tunmx** [comment]
.hyperlpr3 in your system's user directory
