### ISSUE TITLE
3.0版本的不支持iOS了吗？

### ISSUE THREAD

**Issue by wangjjiawei** [szad670401/HyperLPR#365]

**Comment by tunmx** [comment]
你好，iOS版本的demo我们还在开发中，这几天会上传；iOS版本的framework已经提前上传了，如果你急需可以先使用它，并参考linux的demo去调用算法的c_api接口，各个版本的接口是一致的

**Comment by wangjjiawei** [comment]
好的，linux的前段时间研究过，c++动态库也打出来的，我再研究下iOS项目中的使用。很棒的项目👍，后续也会持续关注你们的项目更新情况

**Comment by tunmx** [comment]
好的，感谢支持，iOS的demo如果测试通过了立即会上传，请持续关注项目最新的提交 谢谢！

**Comment by kennenfromchina** [comment]
> 好的，linux的前段时间研究过，c++动态库也打出来的，我再研究下iOS项目中的使用。很棒的项目👍，后续也会持续关注你们的项目更新情况

你好，iOS版本的车牌识别怎么用啊？
