### ISSUE TITLE
在flask web应用中报错

### ISSUE THREAD

**Issue by BigabilityLiu** [szad670401/HyperLPR#37]
当我在flask应用中使用方法时报错，代码如下：
```python
@app.route('/test', methods=['GET'])
def test():
    image = cv2.imread('static/images/006vT0dkzy73eTACbIh15.jpg')
    image, res = pp.SimpleRecognizePlate(image)
    return jsonify(res)
```
错误信息如下：
<img width="1650" alt="error" src="https://user-images.githubusercontent.com/14973015/36070928-b2d4e3f6-0f40-11e8-8f03-6a1d0466cadb.png">
如果我哪里做错了指点，谢谢

**Comment by BigabilityLiu** [comment]
我使用的是python3.6，使用到的各个库版本如下：
- Keras (2.1.3) 
- tensorflow (1.5.0)
- numpy (1.14.0)
- scipy (1.0.0)
- opencv-python (3.4.0.12)
- scikit-image (0.13.1)
- Pillow (5.0.0)

**Comment by BigabilityLiu** [comment]
在flask应用中设置`debug=Flase`就可以正常使用了。但是具体原因还不清楚

**Comment by jozhn** [comment]
你false写成flase了hhh~ 不过我加不加都跟你一样的错误，请问能把完整代码发一下吗

**Comment by BigabilityLiu** [comment]
@jozhn flask代码倒是不多也不难，工程中我部分修改了hyperLPR代码里的model文件路径，你先试试吧，
```python
#coding=utf-8

import numpy
import cv2
from model.hyperlpr.hyperlpr_py3 import pipline as pp
from flask import Flask, request, render_template, jsonify, Response
from werkzeug.utils import secure_filename

app = Flask(__name__)

RESOURCE_FOLDER = 'static/resources/'
IMAGES_FOLDER = 'static/images/'

ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg', 'bmp'])

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS


@app.route('/')
def hello_world():
    return 'Hello World!'


@app.route('/predict', methods=['POST'])
def predict():
    print('predict')
    if 'image' in request.files:
        image = request.files['image']
        if image.filename != '':
            if image and allowed_file(image.filename):
                # read image file string data
                image_str = image.read()
                # convert string data to numpy array
                npimg = numpy.fromstring(image_str, numpy.uint8)
                # convert numpy array to image
                img = cv2.imdecode(npimg, cv2.IMREAD_COLOR)
                image_return, res = pp.SimpleRecognizePlateByE2E(img)
                response = jsonify(res)
                response.headers.add('Access-Control-Allow-Origin', '*')
                return response
            else:
                return 'Only support image with type .png,or .jpg,or .jpeg,or .bmp.'
        else:
            return 'No selected file.'
    else:
        return 'Empty image.'


if __name__ == '__main__':
    app.run(host='0.0.0.0',port=5000)
```

**Comment by jozhn** [comment]
@BigabilityLiu 感谢

**Comment by Donald-Su** [comment]
在flask的web应用中，遇到下面的错误，使用你的代码也有类似错误，请问当时是否遇到了该问题？

ValueError: Tensor Tensor("activation_25/truediv:0", shape=(?, ?, 1, 84), dtype=float32) is not an element of this graph.

**Comment by panda-lab** [comment]
@Donald-Su  请参考 : https://blog.csdn.net/donaldsy/article/details/95097024

**Comment by zhupengfeivip** [comment]
> @Donald-Su 请参考 : https://blog.csdn.net/donaldsy/article/details/95097024

你好，我也是遇到同样的问题。CSDN中的文章，实在是看不明白.。
操作是按照https://www.jianshu.com/p/7ab673abeaae
在Anaconda中运行，并没有运行flask的步骤啊？ 
如何设置单线程?
请多多指教，谢谢！

**Comment by bjwswang** [comment]
@zhupengfeivip  我在app.run中添加了 `threaded=False`，目前正常
  `  app.run(debug=settings.FLASK_DEBUG,threaded=False)`

**Comment by zhupengfeivip** [comment]
> @zhupengfeivip 我在app.run中添加了 `threaded=False`，目前正常
> ` app.run(debug=settings.FLASK_DEBUG,threaded=False)`

是的。我也是这样解决的。并且代码已提交合并，目前获取最新的zeusees/HyperLPR，问题已经解决。
