### ISSUE TITLE
疑问：算法的配置参数

### ISSUE THREAD

**Issue by superoidlau** [szad670401/HyperLPR#374]
|参数| 含义|
|--| --|
|useHalf|?|
|boxConfThreshold|?|
|nmsThreshold|?|
|recConfidenceThreshold|?|

这几个参数的作用是啥呢？

**Comment by tunmx** [comment]
useHalf是判断是否开启fp16推理的开关，还未适配，暂请先忽略；
boxConfThreshold是检测框的分类置信度阈值
nmsThreshold是检测框非极大值抑制阈值
recConfidenceThreshold是字符识别模型分类置信度阈值
