### ISSUE TITLE
在camerax上的兼容性和识别准确率问题

### ISSUE THREAD

**Issue by superoidlau** [szad670401/HyperLPR#376]
1. 在demo中使用的是已废弃的camera进行举例的，是否说明针对该库，使用camera更好一些？
2. 如果使用camerax的话，是否会影响识别准确率呢？

麻烦看到可以答复一下，谢谢。

**Comment by tunmx** [comment]
1. 使用camera1只是沿用了老版本demo的方式，并没有必然性
2. 理论上更换相机工具不会影响性能，sdk只关心通过接口拿到的数据流是否能正确解码

**Comment by superoidlau** [comment]
谢谢答复。
