### ISSUE TITLE
请问如果要在树莓派上跑python的话要装哪些环境呢？还有是否带的起来？

### ISSUE THREAD

**Issue by eilotluchao** [szad670401/HyperLPR#38]

**Comment by eilotluchao** [comment]
麻烦了，谢谢

**Comment by panda-lab** [comment]
树莓派python没有试过，建议采用c++版本，可移植性比较强。

**Comment by eilotluchao** [comment]
若采用c++版本是否只要安装opencv3.5版本即可？然后在linux直接调用？

**Comment by panda-lab** [comment]
opencv 3.3以上，linux直接可以调用。

**Comment by Jnusujianfeng** [comment]
请问在树莓派上面可以直接盗用hyperlpr库来实现车牌识别吗

**Comment by panda-lab** [comment]
可以，已经有人做过了。

**Comment by Jnusujianfeng** [comment]
有教程推荐吗，感谢了 ，刚入门图像识别很多东西需要看教程才能摸懂

**Comment by panda-lab** [comment]
@Jnusujianfeng  采用prj-linux中的代码，编译到树莓派即可。

**Comment by Jnusujianfeng** [comment]
请问编译prj-linux中代码是否带有python接口，可以在树莓派中使用python调用工程？

**Comment by panda-lab** [comment]
prj-linux没有python接口
