### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libhyperlpr3.so" not found

### ISSUE THREAD

**Issue by BGMyang** [szad670401/HyperLPR#396]
根据SDK拉取工程步骤，在AVD运行时出现 HyperLPR-Example keeps stopping
查看log发现：java.lang.UnsatisfiedLinkError: dlopen failed: library "libhyperlpr3.so" not found
这该咋办啊

**Comment by BGMyang** [comment]
该如何找到这个.so文件，依赖也加了全按照步骤做的

**Comment by tunmx** [comment]
目前仓库提供的so只支持arm64-v8a和armeabi-v7a版本的CPU架构，如果你使用AVD提示无法找到so的问题，可能是因为模拟器是使用x86架构，要解决问题可能需要：1. 自行编译x86版本的所有依赖库和libhyperlpr3.so；2. 使用真机调试

**Comment by BGMyang** [comment]
好的谢谢
