### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

### ISSUE THREAD

**Issue by xilinggrantli** [szad670401/HyperLPR#41]
远程连接到工作站运行代码，原始代码中的输出带有中文，会有“UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
”这个报错，但是我直接在工作站的命令行中运行就不会有这个报错。想知道有没有人遇到过类似的问题？该如何解决（已经尝试了encode/decode，sys等方法都无法解决）？

**Comment by szad670401** [comment]
尝试使用新更新的代码。
