### ISSUE TITLE
Linux 下编译成功后运行./TRST_PIPLINE出现如下错误 OpenCV Error

### ISSUE THREAD

**Issue by gyqworld** [szad670401/HyperLPR#47]
OpenCV Error: Unspecified error (FAILED: fs.is_open(). Can't open "model/HorizonalFinemapping.prototxt") in ReadProtoFromTextFile, file /home/firefly/opencv-3.3.0/modules/dnn/src/caffe/caffe_io.cpp, line 1113
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/firefly/opencv-3.3.0/modules/dnn/src/caffe/caffe_io.cpp:1113: error: (-2) FAILED: fs.is_open(). Can't open "model/HorizonalFinemapping.prototxt" in function ReadProtoFromTextFile

Aborted (core dumped)

**Comment by gyqworld** [comment]
解压Prj-Linux 下model 文件夹中Archive.zip 文件 到当前目录

**Comment by panlanlan** [comment]
您好 请问 你这个问题解决了吗

**Comment by panlanlan** [comment]
我也碰到了这这个问题 但是不知道怎么解决
