### ISSUE TITLE
为什么这个项目会内存泄露？

### ISSUE THREAD

**Issue by how0723** [szad670401/HyperLPR#48]
为什么这个项目会内存泄露？

**Comment by panda-lab** [comment]
@how0723 提供一下log，或者告诉我们一下泄露位置，谢谢。

**Comment by how0723** [comment]
pr::PipelinePR 对象在析构时有资源没有释放，如果在一个for循环中创建了pr::PipelinePR对象，内存会一直升高

**Comment by panda-lab** [comment]
@how0723 好的，我看一下，你那里能改吗，要是已经修正的话直接给我发下代码怎么样？

**Comment by how0723** [comment]
@lsy17096535 我还没有找到bug

**Comment by panda-lab** [comment]
这个问题我们在多个平台排查，没有发现内存泄露。
