### ISSUE TITLE
Is HyperLPRLite Trained by HyperLPR-training?

### ISSUE THREAD

**Issue by wangsssky** [szad670401/HyperLPR#51]
There are several references of training codes in the readme.md. Is there a list that shows which model is trained by which code? Thanks in advance.

**Comment by panda-lab** [comment]
you can refer https://github.com/armaab/hyperlpr-train

**Comment by soufianesabiri** [comment]
Please, the hyperlpr-train is not using GRU, but HyperLPR is using GRU; CAN YOU PROVIDE CODE?

**Comment by panda-lab** [comment]
@soufianesabiri  hyperlpr-train is segmentation based code. if you want to train cnn e2e model, you can try https://github.com/armaab/hyperlpr-train
