### ISSUE TITLE
车牌粗定位

### ISSUE THREAD

**Issue by shuaibijun** [szad670401/HyperLPR#53]
车牌粗定位的具体过程是怎样的，感觉博客写的太简洁了看得有点懵

**Comment by JimmyJuan** [comment]
建议自行搜索google scholar, 关键词: license plate recognition. 比如博客里的文章地址在: http://wineyard.in/Abstract/mtech/Embedded/bp/13EM9.pdf
文章名: Automatic license plate recognition (ALPR): A state-of-the-art review

**Comment by panda-lab** [comment]
可以采用ssd.mtcnn,yolo,或者传统方式的adaboost cascade等。
