### ISSUE TITLE
运行新版本出错

### ISSUE THREAD

**Issue by shuaibijun** [szad670401/HyperLPR#55]
运行新版本时报错name 'drawRectBox' is not defined，百度谷歌都查了也不明白是少了什么库，求解答

**Comment by HavendGithub** [comment]
这应该不是少了什么库，而是一个自己定义的函数，在demo里有，如果是not defined的话，我觉得你用这个函数的时候打错了了

**Comment by panda-lab** [comment]
已经更新 drawRectbox函数
