### ISSUE TITLE
核心问题关于三个文件的产生（"model/cascade.xml", "model/model12.h5", "model/ocr_plate_all_gru.h5"）

### ISSUE THREAD

**Issue by HavendGithub** [szad670401/HyperLPR#56]
能问一下那个 config.json 的文件是怎么回事吗？

**Comment by HavendGithub** [comment]
还有"model/cascade.xml", "model/model12.h5", "model/ocr_plate_all_gru.h5"这三个文件是怎么产生的呢？

**Comment by haoxinl** [comment]
model/cascade.xml的话我感觉应该是自己训练的，或者是作者直接拿别人训练过的来用，反正opencv库中只带了人脸检测的cascade库。训练过程可以参考https://blog.csdn.net/zhaocj/article/details/54412080

**Comment by panda-lab** [comment]
这三个都要自己训练

**Comment by peach1995** [comment]
想问一下，作者在readme里面的“添加的新的Python 序列模型-识别率大幅提高(尤其汉字)(2018.3.12)”对应的代码是哪一个，想试试

**Comment by szad670401** [comment]
config.json是测试时的配置文件。
