### ISSUE TITLE
请问代码是用python2的语法写的，这样配python3环境不是需要改动很多吗？

### ISSUE THREAD

**Issue by panyan928** [szad670401/HyperLPR#57]
如题，想知道大家是怎么解决这个的？有没有什么方便的方法？

**Comment by panda-lab** [comment]
有python3的代码，可以采用该代码。

**Comment by panyan928** [comment]
诶？哪里有呢？
我直接clone这里的，没看到呢，用了python自带的脚本转换。

**Comment by panda-lab** [comment]
https://github.com/zeusees/HyperLPR/tree/master/hyperlpr_py3
