### ISSUE TITLE
尝试训练ctc模型，很快就显示loss：nan，请问可能是什么原因

### ISSUE THREAD

**Issue by paul8765** [szad670401/HyperLPR#59]
训练样本接近1万，是样本少吗，请问可以公开一下训练样本吗

**Comment by ShaneYS** [comment]
首先尝试降低学习率

**Comment by ys707221924** [comment]
首先尝试降低学习率

**Comment by Pau1code** [comment]
降低了学习率，还是显示loss : nan

**Comment by panda-lab** [comment]
你的参数怎么设置的

**Comment by Pau1code** [comment]
因为样本量较少，因此batch为2， 学习率为0.005

**Comment by panda-lab** [comment]
batch太小了

**Comment by Pau1code** [comment]
@lsy17096535 提升batch至16， 但还是没有loss值，模型中是直接调用keras中的ctc_batch_cost计算loss值应该不存在无法计算的问题，是因为没有初始权重的原因吗？

**Comment by szad670401** [comment]
尝试把batchsize提高到100以上。
