### ISSUE TITLE
支持卡车黄牌的双排排列的车牌吗？

### ISSUE THREAD

**Issue by aguang1201** [szad670401/HyperLPR#67]
如题，我在卡车的黄牌上测试，一排的能识别，两排的没有识别出结果。例如：
粤 Ｊ
33333
请问训练集是否包括这种车牌？

**Comment by panda-lab** [comment]
目前开源版本还不能识别黄色双层车牌

**Comment by aguang1201** [comment]
收到，收集图片，再训练。

**Comment by hdmjdp** [comment]
请问下，该项目支持双排车的训练吗，如果支持可否指导下如何训练，谢谢

**Comment by little2Rabbit** [comment]
@aguang1201 双层黄牌你搞定了吗，你是怎么弄的可以提供下思路吗

**Comment by ys-tech** [comment]
@qq542288564 我的想法是先做object detection，分成上下两部分，每个部分做CNN+LSTM。不过没数据，做不起来。

**Comment by aguang1201** [comment]
@qq542288564 我的想法是先做object detection，分成上下两部分，每个部分做CNN+LSTM。不过没数据，做不起来。
