### ISSUE TITLE
GRU training code

### ISSUE THREAD

**Issue by wjtan99** [szad670401/HyperLPR#69]
Can you open source the GRU training code?  Thanks a lot

**Comment by szad670401** [comment]
gru trainng code based on this article
https://zhuanlan.zhihu.com/p/26078299?utm_source=tuicool&utm_medium=referral

**Comment by szad670401** [comment]
I found GRU or RNN seris unit has bad performance in license-plate like task.

**Comment by wjtan99** [comment]
thanks.
