### ISSUE TITLE
how to train HyperLPR

### ISSUE THREAD

**Issue by lichenguang302** [szad670401/HyperLPR#7]
hi @szad670401
有什么办法去train HyperLPR吗，最近在使用HyperLPR发现有时候识别率不是很高，想知道是否有办法去train一下HyperLPR,好提高识别率

**Comment by lichenguang302** [comment]
hello?

**Comment by panda-lab** [comment]
@lichenguang302  try our ene-to-end model.

**Comment by lichenguang302** [comment]
@lsy17096535 you mean the other project end-to-end-for-chinese-plate-recognition?

**Comment by panda-lab** [comment]
@lichenguang302  we have update this with end-to-end model, see readme.

**Comment by lichenguang302** [comment]
sorry, i just noticed that, thank your patience！  @lsy17096535
