### ISSUE TITLE
关于top_bottom_padding_rate的疑问

### ISSUE THREAD

**Issue by aguang1201** [szad670401/HyperLPR#70]
请问在HyperLPRLite.py中第152行代码：images = self.detectPlateRough(image, image.shape[0], top_bottom_padding_rate=0.1)中top_bottom_padding_rate的作用是什么？感觉只是为了删除上下的多余区域．如果是这个作用，为什么没有删除左右多余区域的比例参数．另外，如果车牌靠近图片边缘的话，这样删除不是有可能把车牌信息删掉吗？

**Comment by szad670401** [comment]
是测试从车牌识别相机输出的卡口图片
 cascade误检会比较严重。所以设置了margin。
