### ISSUE TITLE
Android  版出来的效果跟那个体验版的app识别率也相差太远了吧

### ISSUE THREAD

**Issue by yangkezun** [szad670401/HyperLPR#74]
Android  版出来的效果跟那个体验版的app识别率也相差太远了吧

**Comment by panda-lab** [comment]
请尝试我们提供的端到端android工程

**Comment by yangkezun** [comment]
@lsy17096535  https://github.com/zeusees/HyperLPR/tree/master/Prj-Android/app  
是这个吗

**Comment by panda-lab** [comment]
是的

**Comment by yangkezun** [comment]
@lsy17096535  嗯好 。这个还要配吧，我看CmakeLists.txt都不对

**Comment by yangkezun** [comment]
@lsy17096535  端到端的Android 工程依赖opencv-3.4.1-android-sdk吗

**Comment by yangkezun** [comment]
@lsy17096535  android 端对端的版本c++代码是不是不全的？ javaWarpper.cpp 调用函数参数数量不对

**Comment by panda-lab** [comment]
已经更新了android版端到端的代码，欢迎查看。

**Comment by EchoXBR** [comment]
> @lsy17096535 https://github.com/zeusees/HyperLPR/tree/master/Prj-Android/app
> 是这个吗

这个好用吗 我用这个编译出来的apk 和体验版的apk 差别很大呀
