### ISSUE TITLE
android 端对端的版本c++代码是不是不全的？

### ISSUE THREAD

**Issue by yangkezun** [szad670401/HyperLPR#75]
E:\Freinds\HyperLPR\app\src\main\cpp\javaWarpper.cpp:50:30: error: no matching constructor for initialization of 'pr::PipelinePR'
    pr::PipelinePR *PR = new pr::PipelinePR(detector_path,

确实没有那个构造函数

**Comment by panda-lab** [comment]
已经更新了android实现，欢迎查看。
