### ISSUE TITLE
GPU error: swig/python detected a memory leak of type 'int64_t *', no destructor found

### ISSUE THREAD

**Issue by Liuyubao** [szad670401/HyperLPR#76]
I used Nvidia Tesla P4 to run the example and got this error.

When I use cpu, it runs without error.

![image](https://user-images.githubusercontent.com/16116613/42007989-d2c74b78-7ab5-11e8-8ce8-77e9440e63b3.png)
![image](https://user-images.githubusercontent.com/16116613/42007997-d91724f8-7ab5-11e8-8a03-66f71c0d0acc.png)

**Comment by szad670401** [comment]
the new update can support install from pypi via pip ,the dnn inference part is powerd by opencv dnn.
you can compile opencv-python with opencl  or use halide to accelerate with gpu.
