### ISSUE TITLE
小编 android端对端的工程不能识别

### ISSUE THREAD

**Issue by yangkezun** [szad670401/HyperLPR#77]
你做天跟我说的android端对端的工程，已经跑起来了，但是识别图片的时候有问题，直接崩溃。LOG如下：
06-28 16:31:47.954 22539-22539/pr.platerecognization E/cv::error(): OpenCV Error: Assertion failed (ngroups > 0 && inpCn % ngroups == 0 && outCn % ngroups == 0) in virtual bool cv::dnn::ConvolutionLayerImpl::getMemoryShapes(const std::vector<std::vector<int> >&, int, std::vector<std::vector<int> >&, std::vector<std::vector<int> >&) const, file /build/master_pack-android/opencv/modules/dnn/src/layers/convolution_layer.cpp, line 199
06-28 16:31:47.955 22539-22539/pr.platerecognization A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 22539 (terecognization)

**Comment by szad670401** [comment]
确保模型已经载入。
