### ISSUE TITLE
c++版只能识别蓝牌，获取不到车牌颜色，识别率很低

### ISSUE THREAD

**Issue by duyunnan** [szad670401/HyperLPR#78]
c++版只能识别蓝牌，获取不到车牌颜色，识别率很低

**Comment by peach1995** [comment]
C++版的颜色需要自己另加，识别率在排除定位，切割等影响时基本字符识别的话，有78%左右的正确率。

不知道你有没有试过他提供的 “添加的新的Python 序列模型-识别率大幅提高(尤其汉字)(2018.3.12)” 这个模型，想知道这一版的正确率是多少
