### ISSUE TITLE
可以稍微介绍一下最新orc_plate_all_gru.h5和model12.h5的训练过程吗？

### ISSUE THREAD

**Issue by deepblacksky** [szad670401/HyperLPR#83]
可以稍微介绍一下最新orc_plate_all_gru.h5和model12.h5的训练过程吗，训练流程和需要准备的数据的格式，能介绍一下吗？

**Comment by peach1995** [comment]
想请教一下，model12.h5是作者在readme里提到的 识别率有大幅度提高（尤其汉字）的模型吗？

**Comment by panda-lab** [comment]
@peach1995 是的。

**Comment by deepblacksky** [comment]
@lsy17096535 您好，您能大体介绍一下训练过程吗，训练数据格式之类的，谢谢。

**Comment by little2Rabbit** [comment]
@peach1995 你训练了吗  我也想看看是怎么写的
