### ISSUE TITLE
python序列模型识别率提高问题

### ISSUE THREAD

**Issue by peach1995** [szad670401/HyperLPR#84]
readme中写：“添加的新的Python 序列模型-识别率大幅提高(尤其汉字)(2018.3.12)”
想问这是哪个模型，我比较demo.py的模型测试结果和C++版本的模型测试结果，发现差不多，没有很大进步。想知道具体是哪一个模型，是不是model12.h5

**Comment by panda-lab** [comment]
这个模型对蓝牌的识别率较好

**Comment by peach1995** [comment]
谢谢你的回答。不过我测试了193张蓝色车牌图片，用C++模型测出来是78%的正确率，用python模型（model = pr.LPR("model/cascade.xml", "model/model12.h5", "model/ocr_plate_all_gru.h5")
）测出来是72%的正确率。是python的模型选的不对吗？

**Comment by ChunfangWang** [comment]
@lsy17096535 同样的疑问 

`model/ocr_plate_all_gru.h5` 这个CNN + RNN的序列模型

我的理解： 基于GRU的RNN部分学习到的应该是 中文车牌的 语法，比如普通车牌，第一位是中文字符，第二位和第三位是字母，第四到第七位是 数字

楼主在ReadMe中提到，可支持的车牌类型有大约7种https://github.com/zeusees/HyperLPR#%E5%8F%AF%E8%AF%86%E5%88%AB%E5%92%8C%E5%BE%85%E6%94%AF%E6%8C%81%E7%9A%84%E8%BD%A6%E7%89%8C%E7%9A%84%E7%B1%BB%E5%9E%8B

请问 不同的车牌，需要训练不同的RNN模型，还是　楼主提供的 `model/ocr_plate_all_gru.h5` 这个模型中  已经包含了 以上所支持的车牌的 语法？

谢谢！

**Comment by beizhengren** [comment]
> 谢谢你的回答。不过我测试了193张蓝色车牌图片，用C++模型测出来是78%的正确率，用python模型（model = pr.LPR("model/cascade.xml", "model/model12.h5", "model/ocr_plate_all_gru.h5")
> ）测出来是72%的正确率。是python的模型选的不对吗？

您好，请问如何进行测试，要怎样运行呢？十分感谢！
