### ISSUE TITLE
安卓版本的编译一直不通过

### ISSUE THREAD

**Issue by lbb1993** [szad670401/HyperLPR#88]
求补全opencv的依赖库和cmake文件，以及build.gradle文件。自己瞎配置，一直编译不通过

**Comment by panda-lab** [comment]
我们看一下，稍等。

**Comment by lbb1993** [comment]
你好，我编译通过了已经，非常感谢您能回复我。我还想报告一个问题，直接下载的apk有次数限制，一定次数之后要重启app，自己编译的没有次数限制貌似。

**Comment by panda-lab** [comment]
修改了哪里编译通过了？方便的话提交各pr可以么？

**Comment by lbb1993** [comment]
瞎鼓捣了两天，主要是添加opencv的库，按照提示修改了代码中的一些编译错误。我有时间了把代码整理一弄一下

**Comment by ablezhong** [comment]
android 中虽然可以编译成功，但是运行时候回报错，原因好像是模型文件没有放进去，导致出现问题。

**Comment by lbb1993** [comment]
模型文件在assets下的,我看了一下是存在的，运行时会拷贝到手机内存里，需要有读写内存卡权限

**Comment by lbb1993** [comment]
我特地下载运行了一下，使用的pixel一代8.0系统可以运行没有问题

**Comment by ablezhong** [comment]
Prj-Android中asserts里面只有一个cascade.xml文件，灭有其他的模型文件，会报错的。

**Comment by 0830arthur** [comment]
"PlateRecognition.java" 中的這行代碼出錯 ===> System.loadLibrary("hyperlpr");
找不到 hyperlpr. 請問該如何取得這 Library??
