### ISSUE TITLE
关于detectRough部分 没有选用 MobileNetSSD

### ISSUE THREAD

**Issue by ChunfangWang** [szad670401/HyperLPR#90]
楼主在另一个repository https://github.com/zeusees/Mobilenet-SSD-License-Plate-Detection
中分享了用SSD做检测的模型，

好奇 为什么在HyperLPR中使用cascade 而没有使用 SSD，可以分享一下这两种检测方法在实验中的效果比较，为什么没有选用SSD的原因吗？感谢！

**Comment by panda-lab** [comment]
SSD定位速度慢 适合有GPU的用户

**Comment by ChunfangWang** [comment]
@lsy17096535 感谢你的回答

SSD出来的结果在我自己的数据集上　要比 cascade 得到的矩形框 更精准一些，对于整个 detection加recognition的部分，detection的准确度对 recognition的最后结果影响大吗？

另想请教一下:  

1.  SSD出来的结果 已经带有bounding box区域的feature map，可以 在后续的CNN+RNN recognition部分直接省略CNN compute feature的部分吗？这样一来　是不是可以节约计算量

**Comment by szad670401** [comment]
可以的 端到端的 text spotting 的做法就是这样的。 但是出于 cpu 边缘计算设备考虑 还是选择使用cascade based detector 要 速度快一点。
