### ISSUE TITLE
你好 是否安卓的端到端项目缺少以下这些文件

### ISSUE THREAD

**Issue by wuxifan** [szad670401/HyperLPR#91]
HorizonalFinemapping.prototxt
HorizonalFinemapping.caffemodel
Segmentation.prototxt
Segmentation.caffemodel
CharacterRecognization.prototxt
CharacterRecognization.caffemodel

**Comment by panda-lab** [comment]
是的，手动拷贝进去。

**Comment by wuxifan** [comment]
-.-你好  还想问下 我是从下面安卓完善版本那边copy过来的 这几个文件是做什么用的?谢谢
