### ISSUE TITLE
新能源车辆 绿牌 车牌字符不含省份应该为7位 

### ISSUE THREAD

**Issue by HaishengLiang** [szad670401/HyperLPR#92]
测试结果为 6位 
希望得到结果位 7位

**Comment by panda-lab** [comment]
把你的测试图片在群里提供一下吧，按理说新能源车牌的识别没有问题。

**Comment by hayt0n** [comment]
遇到了同样的问题
e2e识别出来是正确的，但是最后校正完出来是少了一位

![k](https://user-images.githubusercontent.com/5023850/46793257-dc8f9600-cd77-11e8-95c5-a0757d877f98.jpeg)
原图如下：
![ttt5](https://user-images.githubusercontent.com/5023850/46793322-034dcc80-cd78-11e8-9315-dd17cb2a5f53.jpg)

**Comment by wannaRunaway** [comment]
使用端到端识别
