### ISSUE TITLE
在小米Mix 2S上无法运行？

### ISSUE THREAD

**Issue by xugaoxiang** [szad670401/HyperLPR#94]
Mix 2S手机，android 8.0，打开app一直显示白屏?

**Comment by panda-lab** [comment]
目前在android 7.0手机上运行没有问题，其他版本有可能需要自己做一下适配，编译源码使用。

**Comment by helloworld10010** [comment]
> 目前在android 7.0手机上运行没有问题，其他版本有可能需要自己做一下适配，编译源码使用。

那么怎么编译呢...

**Comment by panda-lab** [comment]
HyperLPR里面有一个Prj-Android，编译这个项目，里面有完整代码，然后把linux/model下的模型文件拷贝到assert文件夹下即可。

**Comment by helloworld10010** [comment]
> Mix 2S手机，android 8.0，打开app一直显示白屏?
我小米6 9.0
我发现是asset中的文件无法复制到sdcard上，后续无法读取导致的。 我手动push文件到sdcard上，第一次可以用，再进又报file not found了，文件明明还在呀，不知道有什么吭

**Comment by helloworld10010** [comment]
> Mix 2S手机，android 8.0，打开app一直显示白屏?

小米6 9.0
白屏根本原因是程序无法读取模型文件，asset中的文件复制到sdcard中时出现问题，具体什么坑我没摸清楚

**Comment by helloworld10010** [comment]
> Mix 2S手机，android 8.0，打开app一直显示白屏?

小米6 9.0
白屏根本原因是程序无法读取模型文件，asset中的文件复制到sdcard中时出现问题，具体什么坑我没摸清楚。 我手动push asset/pr到sdcard 后，屏蔽`copyFilesFromAssets(this, assetPath, sdcardPath);` ，运行正常
