### ISSUE TITLE
识别车牌正确，但是坐标位置不正确。

### ISSUE THREAD

**Issue by BofengDuke** [szad670401/HyperLPR#95]
使用HyperLPR_PlateRecogntion时，车牌可以识别正确，但是返回的坐标有一部分是不正确的。特别是 ymin 和 ymax ，偏差极大。

**Comment by szad670401** [comment]
坐标是没做校准的，只是extend后的。回头我会更新一下。

**Comment by everett-moon** [comment]
我实际测试时也发现了这个问题
