### ISSUE TITLE
关于双层黄牌车的识别

### ISSUE THREAD

**Issue by hdmjdp** [szad670401/HyperLPR#96]
请问下，该项目支持双排车的训练吗，如果支持可否指导下如何训练，谢谢

**Comment by panda-lab** [comment]
目前我们的版本没有提供双层的识别，你可以采用我们的训练代码，自己训练双层的检测跟识别。

**Comment by hdmjdp** [comment]
好的谢谢，你们训练的代码中，好像没有车牌检测部分的训练代码

**Comment by hdmjdp** [comment]
>           目前我们的版本没有提供双层的识别，你可以采用我们的训练代码，自己训练双层的检测跟识别。

好的谢谢，你们训练的代码中，好像没有车牌检测部分的训练代码

**Comment by panda-lab** [comment]
https://github.com/zeusees/train-detector
