### ISSUE TITLE
怎么在c++中调用python模型

### ISSUE THREAD

**Issue by hdmjdp** [szad670401/HyperLPR#97]

**Comment by hdmjdp** [comment]
cpp版本精度明显不如python版本，故请问下，C++怎么解析python训练好的模型

**Comment by szad670401** [comment]
cpp用segmentation free inception 这个model要比python版本好很多

**Comment by hdmjdp** [comment]
感谢。对了问下，我可以在你的cascade.xml的基础上进行finetune训练吗。貌似opencv的train代码没有提供这个接口

**Comment by panda-lab** [comment]
不可以
