### ISSUE TITLE
使用这个代码以来遇到的错误真的不是一般的多，目前还未解决，请教各位大神

### ISSUE THREAD

**Issue by panlanlan** [szad670401/HyperLPR#99]
1 Segmentation fault (core dumped)
2  OpenCV Error: One of arguments' values is out of range (Bad new number of rows) in reshape, file /home/nvidia/opencv330/modules/core/src/matrix.cpp, line 1095
3  OpenCV Error: Assertion failed (0 <= _colRange.start && _colRange.start <= _colRange.end && _colRange.end <= m.cols) in Mat, file /home/nvidia/opencv330/modules/core/src/matrix.cpp, line 497

**Comment by fortdam** [comment]
Which code are u mention?

在 2018年9月17日，16:41，panlanlan <notifications@github.com<mailto:notifications@github.com>> 写道：


1 Segmentation fault (core dumped)
2 OpenCV Error: One of arguments' values is out of range (Bad new number of rows) in reshape, file /home/nvidia/opencv330/modules/core/src/matrix.cpp, line 1095
3 OpenCV Error: Assertion failed (0 <= _colRange.start && _colRange.start <= _colRange.end && _colRange.end <= m.cols) in Mat, file /home/nvidia/opencv330/modules/core/src/matrix.cpp, line 497

**Comment by panlanlan** [comment]
linux c++

**Comment by szad670401** [comment]
try to use 3.4.x to compile.

**Comment by panlanlan** [comment]
i used 3.4.2 to compile it but it still had the error

         `Segmentation` fault (core dumped)
